const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('../app/social-model.js'),C=require('../app/core.js');
const clone=v=>JSON.parse(JSON.stringify(v));
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function harness(premium=true){
 let sequence=0,confirmation,failed=false;
 const navigation=[],messages=[],G={data:{social:M.initial()},ui:{page:'social',groupId:null},pages:{},actions:{},forms:{},e:escape,icon:n=>`<i>${n}</i>`,fmt:String,dateLabel:String,today:()=> '2026-09-25',uid:()=>`id-${++sequence}`,isPremium:()=>premium,
  button:(label,page,params={},cls='')=>`<button data-go="${page}" data-params="${escape(JSON.stringify(params))}" class="${cls}">${label}</button>`,header:(ey,title,back)=>`<header data-back="${back||''}">${escape(ey)} ${escape(title)}</header>`,section:(title,link='')=>`<h2>${title}</h2>${link}`,
  navigate(page,params={}){Object.assign(G.ui,params,{page});navigation.push({page,...params});},toast:m=>messages.push(m),copyText:async()=>{},confirm(title,text,callback){confirmation={title,text,callback};},
  async commit(mutator){if(failed)return false;const next=clone(G.data);mutator(next);M.validate(next.social);G.data=next;return true;}
 };
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../app/social.js'),'utf8'),{Gym:G,GymSocialModel:M,GymCore:C});
 return {G,navigation,messages,get confirmation(){return confirmation;},set failSave(value){failed=value;}};
}
const form=values=>({elements:Object.fromEntries(Object.entries(values).map(([k,value])=>[k,{value}]))});
const addGroup=h=>{M.createGroup(h.G.data.social,{id:'friends',name:'Friday friends'},true);h.G.ui.groupId='friends';};
const challengeValues={title:'Private bench goal',metric:'kg',target:'80',start:'2026-09-01',end:'2026-09-30'};
function addChallenge(h){M.createChallenge(h.G.data.social,{...challengeValues,id:'bench',groupId:'friends',target:80},true);h.G.ui.challengeId='bench';}
test('root lists friend groups while the goals are only inside their group',()=>{const h=harness();addGroup(h);addChallenge(h);const root=h.G.pages.social();assert.match(root,/Vriendengroepen/);assert.match(root,/Friday friends/);assert.doesNotMatch(root,/Private bench goal|Challengecode invoeren|social-new-challenge/);const group=h.G.pages.socialGroup();assert.match(group,/Private bench goal/);assert.match(group,/&quot;challengeId&quot;:&quot;bench&quot;,&quot;groupId&quot;:&quot;friends&quot;/);});
test('challenge form preserves group context after save and does not navigate on failed storage',async()=>{const h=harness();addGroup(h);h.G.ui.page='socialChallengeNew';h.failSave=true;await h.G.forms['social-challenge'](form(challengeValues));assert.equal(h.navigation.length,0);assert.equal(h.G.data.social.challenges.length,0);h.failSave=false;await h.G.forms['social-challenge'](form(challengeValues));assert.equal(h.G.ui.page,'socialChallenge');assert.equal(h.G.ui.groupId,'friends');assert.equal(h.G.data.social.challenges[0].groupId,'friends');});
test('free joining requires explicit confirmation and opens the imported friend group',async()=>{const source=harness();addGroup(source);addChallenge(source);const h=harness(false),code=M.groupCode(source.G.data.social,'friends');h.G.forms['social-join-preview'](form({code}));assert.equal(h.G.data.social.groups.length,0);assert.match(h.confirmation.text,/Bestaande scores blijven behouden/);await h.confirmation.callback();assert.equal(h.G.ui.page,'socialGroup');assert.equal(h.G.ui.groupId,'friends');assert.equal(h.G.data.social.challenges[0].groupId,'friends');assert.equal(h.navigation.some(n=>n.page==='premium'),false);});
test('free imported participants can save scores while create actions go through the Premium gate',async()=>{const source=harness();addGroup(source);addChallenge(source);const h=harness(false);M.joinGroup(h.G.data.social,M.groupCode(source.G.data.social,'friends'));h.G.ui.groupId='friends';h.G.ui.challengeId='bench';await h.G.forms['social-score'](form({memberId:'self',value:'65',date:'2026-09-25',note:''}));assert.equal(h.G.data.social.challenges[0].entries[0].value,65);h.G.actions['social-new-challenge']();assert.equal(h.G.ui.page,'premium');assert.equal(h.G.data.social.challenges.length,1);});
test('leaving a challenge returns to its friend group and preserves unrelated data',async()=>{const h=harness();addGroup(h);addChallenge(h);h.G.ui.page='socialChallenge';h.G.actions['social-delete-challenge']();assert.equal(h.G.data.social.challenges.length,1);await h.confirmation.callback();assert.equal(h.G.ui.page,'socialGroup');assert.equal(h.G.ui.groupId,'friends');assert.equal(h.G.data.social.groups.length,1);assert.equal(h.G.data.social.challenges.length,0);});
test('old free users can read their archived results without buying Premium or obtaining a group code',()=>{const h=harness(false);h.G.data.social.legacyChallenges.push({...challengeValues,id:'old',target:80,groupId:null,origin:'joined',members:[{id:'self',name:'Ik'}],entries:[{id:'saved',memberId:'self',value:72,date:'2026-09-25',note:'Preserved note'}]});M.validate(h.G.data.social);const html=h.G.pages.social();assert.match(html,/<details class="social-legacy-import"><summary>Eerdere challenges \(1\)/);assert.match(html,/72 kg/);assert.match(html,/Preserved note/);assert.doesNotMatch(html,/social-score|social-new-challenge/);assert.equal(h.navigation.length,0);});
