(function(){
 'use strict';
 const G=window.Gym,M=window.GymAIPlan,e=G.e;
 const draft={stage:1,preferences:{goal:'muscle',equipment:'gym',experience:'beginner',days:[0,2,4],minutes:45,notes:''},prompt:'',answer:'',preview:null,error:''};
 const options=(values,selected)=>Object.entries(values).map(([value,label])=>`<option value="${e(value)}" ${value===selected?'selected':''}>${e(label)}</option>`).join('');
 const action=(label,name,cls='primary')=>`<button type="button" class="${cls}" data-action="${name}">${label}</button>`;
 function steps(){return `<ol class="ai-steps" aria-label="Stappen voor je AI-plan">${['Jouw wensen','Eigen AI','Controleer'].map((label,i)=>`<li ${draft.stage===i+1?'aria-current="step"':''}><span>${i+1}</span>${label}</li>`).join('')}</ol>`;}
 function choiceForm(){const p=draft.preferences;return `<p>Kies je wensen. We maken een prompt die je zelf in een AI-app naar keuze plakt.</p><form class="fields ai-preferences" data-form="ai-preferences"><label>Wat is je trainingsdoel?<select name="goal">${options(M.GOALS,p.goal)}</select></label><div class="pair"><label>Je ervaring<select name="experience">${options(M.EXPERIENCE,p.experience)}</select></label><label>Tijd per training<select name="minutes">${M.MINUTES.map(n=>`<option value="${n}" ${n===p.minutes?'selected':''}>${n} minuten</option>`).join('')}</select></label></div><label>Beschikbaar materiaal<select name="equipment">${options(M.EQUIPMENT,p.equipment)}</select></label><fieldset class="ai-weekdays"><legend>Op welke dagen wil je trainen?</legend><div>${M.DAYS.map((name,i)=>`<label><input type="checkbox" name="days" value="${i}" ${p.days.includes(i)?'checked':''}><span>${name.slice(0,2)}</span><span class="ai-sr-only">${e(name.slice(2))}</span></label>`).join('')}</div></fieldset><label>Aanvullende wensen <span class="muted">Optioneel · maximaal 1.000 tekens</span><textarea name="notes" maxlength="1000" placeholder="Bijvoorbeeld: ik heb alleen dumbbells en train graag mijn schouders.">${e(p.notes)}</textarea></label><p class="ai-privacy">Alleen wat je hier invult komt in de prompt. Je foto’s, metingen en trainingsgeschiedenis worden niet toegevoegd.</p><p class="form-error" role="alert">${e(draft.error)}</p><button type="submit" class="primary">Prompt maken ${G.icon('arrow-right')}</button></form>`;}
 function transfer(){return `<section class="ai-instruction"><span class="ai-number">1</span><div><h2>Kopieer je prompt</h2><p>Plak de prompt in je eigen AI-app, bijvoorbeeld een lokaal model op je toestel of computer.</p></div></section><label class="ai-text-label" for="ai-generated-prompt">Jouw prompt</label><textarea id="ai-generated-prompt" class="code-input ai-prompt" readonly spellcheck="false">${e(draft.prompt)}</textarea>${action(G.icon('copy')+' Prompt kopiëren','ai-copy')}<p class="ai-privacy">Jij kiest waar je de prompt plakt. Of die AI lokaal of online werkt, hangt af van de AI-app die je kiest. Gym Planner verstuurt niets naar een AI-dienst.</p><section class="ai-instruction"><span class="ai-number">2</span><div><h2>Plak het antwoord terug</h2><p>Kopieer het hele JSON-antwoord uit je AI-app. We controleren het formaat voordat je iets opslaat.</p></div></section><form class="fields" data-form="ai-answer"><label>Antwoord van je AI<textarea name="answer" class="code-input ai-answer" maxlength="102400" spellcheck="false" placeholder='{"name":"Mijn trainingsweek","days":{…}}' required>${e(draft.answer)}</textarea></label><p class="form-error" role="alert">${e(draft.error)}</p><button type="submit" class="primary">Plan controleren ${G.icon('arrow-right')}</button></form>${action('Trainingswensen aanpassen','ai-back-preferences','secondary')}`;}
 function preview(){const plan=draft.preview;return `<div class="ai-preview-intro"><span class="eyebrow">VOORBEELD VAN JOUW NIEUWE WEEK</span><h2>${e(plan.name)}</h2><p>Bekijk de oefeningen, sets en herhalingen. Het startgewicht is 0 kg; dat vul je zelf in tijdens je training.</p></div><div class="ai-plan-preview">${plan.days.map((day,i)=>`<section class="ai-plan-day"><div class="ai-day-heading"><h3>${e(M.DAYS[i])}</h3><span>${day.exercises.length?e(day.time):'Rustdag'}</span></div>${day.exercises.length?`<h4>${e(day.name||'Training')}</h4><ul>${day.exercises.map(ex=>`<li><strong>${e(ex.name)}</strong><span>${ex.sets} sets × ${ex.reps} herhalingen · 0 kg</span>${ex.detail?`<p>${e(ex.detail)}</p>`:''}</li>`).join('')}</ul>`:'<p>Geen training ingepland.</p>'}</section>`).join('')}</div><p class="notice">Toepassen vervangt je terugkerende weekschema, inclusief de wekelijkse herinneringen daarin. Eerder gelogde trainingen en dagherinneringen blijven behouden.</p>${action('Dit weekplan toepassen','ai-apply')}${action('Antwoord aanpassen','ai-back-answer','secondary')}${action('Trainingswensen aanpassen','ai-back-preferences','text-button')}`;}
 G.pages.aiPlan=()=>G.header('GRATIS · MET JE EIGEN AI','Jouw AI-plan.','planning')+`<div class="ai-plan-page">${steps()}${draft.stage===1?choiceForm():draft.stage===2?transfer():preview()}</div>`;
 function readPreferences(form){return {goal:form.elements.goal.value,equipment:form.elements.equipment.value,experience:form.elements.experience.value,days:[...form.querySelectorAll('input[name=days]:checked')].map(el=>Number(el.value)),minutes:Number(form.elements.minutes.value),notes:form.elements.notes.value};}
 document.addEventListener('input',ev=>{const form=ev.target.closest('form');if(form?.dataset.form==='ai-preferences')draft.preferences=readPreferences(form);if(form?.dataset.form==='ai-answer'&&ev.target.name==='answer'){draft.answer=ev.target.value;draft.preview=null;}});
 document.addEventListener('change',ev=>{const form=ev.target.closest('form');if(form?.dataset.form==='ai-preferences')draft.preferences=readPreferences(form);});
 G.forms['ai-preferences']=form=>{draft.preferences=readPreferences(form);try{const text=M.prompt(draft.preferences);draft.preferences=M.preferences(draft.preferences);if(text!==draft.prompt){draft.answer='';draft.preview=null;}draft.prompt=text;draft.stage=2;draft.error='';G.render();window.scrollTo(0,0);}catch(err){draft.error=err.message;G.formError(form,draft.error);}};
 G.forms['ai-answer']=form=>{draft.answer=form.elements.answer.value;try{draft.preview=M.parse(draft.answer);draft.stage=3;draft.error='';G.render();window.scrollTo(0,0);}catch(err){draft.preview=null;draft.error=err.message;G.formError(form,draft.error);}};
 G.actions['ai-copy']=async()=>{try{const ok=await G.copyText(draft.prompt);if(ok===false)throw Error('Kopiëren lukt niet. Houd de prompt ingedrukt en kies Kopieer.');G.toast('Prompt gekopieerd. Plak hem in je eigen AI-app.');}catch(err){G.toast(err.message||'Kopiëren lukt niet. Selecteer de prompt en kopieer hem zelf.');}};
 G.actions['ai-back-preferences']=()=>{draft.stage=1;draft.error='';G.render();window.scrollTo(0,0);};
 G.actions['ai-back-answer']=()=>{draft.stage=2;draft.error='';G.render();window.scrollTo(0,0);};
 G.actions['ai-apply']=()=>{if(!draft.preview)return;const plan=JSON.parse(JSON.stringify(draft.preview));G.confirm('Dit weekplan toepassen?',`“${plan.name}” vervangt je weekschema en de wekelijkse herinneringen daarin. Je gelogde trainingen en dagherinneringen blijven behouden.`,async()=>{if(await G.commit(d=>{d.plan=plan;})){G.toast('Weekplan opgeslagen. Je kunt elke dag zelf aanpassen.');G.navigate('planning');}},'Weekplan toepassen');};
})();
