(function(){
 'use strict';
 const C=GymCore,screen=document.getElementById('screen'),nav=document.getElementById('nav'),dialog=document.getElementById('dialog');
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:6}).format(n);
 const icon=n=>`<i data-lucide="${e(n)}" aria-hidden="true"></i>`;
 const dateLabel=d=>C.validDate(d)?new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00')):'—';
 const button=(text,page,params={},className='primary')=>`<button type="button" class="${e(className)}" data-go="${e(page)}" data-params="${e(JSON.stringify(params))}">${text}</button>`;
 const action=(text,name,attrs='',cls='primary')=>`<button type="button" class="${cls}" data-action="${name}" ${attrs}>${text}</button>`;
 const header=(ey,title,back)=>`<header class="page-header">${back?button(icon('arrow-left'),back,{},'icon-button back-button'):'<span class="brand-mark"></span>'}<div class="grow"><span class="eyebrow">${e(ey)}</span><h1>${e(title)}</h1></div>${button(icon('sliders-horizontal'),'settings',{},'icon-button settings-button')}</header>`;
 const empty=(title,text,cta='')=>`<div class="empty"><span class="empty-mark">${icon('plus')}</span><h2>${e(title)}</h2><p>${e(text)}</p>${cta}</div>`;
 const section=(title,link='')=>`<div class="section-head"><h2>${e(title)}</h2>${link}</div>`;
 let queue=Promise.resolve(),loaded=false,toastTimer,confirmCallback;
 const G=window.Gym={data:C.initial(),ui:{page:'today',date:C.today(),weekday:C.weekday(C.today())},pages:{},actions:{},forms:{},afterRender:[],e,fmt,icon,dateLabel,today:C.today,uid:C.uid,button,header,empty,section,
  toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},4200);},
  formError(form,message){let el=form.querySelector('.form-error');if(!el){el=document.createElement('p');el.className='form-error';el.setAttribute('role','alert');form.append(el);}el.textContent=message;},
  confirm(title,text,fn,confirmLabel='Bevestigen'){confirmCallback=fn;dialog.innerHTML=`<h2 id="dialog-title">${e(title)}</h2><p>${e(text)}</p><div class="pair">${action('Annuleren','dialog-cancel','','secondary')}${action(e(confirmLabel),'dialog-confirm','','primary')}</div>`;dialog.showModal();},
  navigate(page,params={}){if(page==='productEdit'&&Object.prototype.hasOwnProperty.call(params,'productId')&&G.ui.page!=='productEdit')G.ui.productDraft=null;if(page==='usage'&&G.ui.page!=='usage')G.ui.usageDraft=null;Object.assign(G.ui,params,{page});render();window.scrollTo(0,0);},render,
  commit(mutator){const run=queue.then(async()=>{if(!loaded){G.toast('Je gegevens zijn nog niet beschikbaar.');return false;}const next=JSON.parse(JSON.stringify(G.data)),hadNotifications=G.data.settings.notifications;try{await mutator(next);validateState(next);await GymStorage.save(next);}catch(err){G.toast(err.message||'Opslaan mislukt. Je vorige gegevens zijn behouden.');return false;}G.data=next;try{render();}catch(err){G.toast('Je gegevens zijn bewaard. Open dit scherm opnieuw.');}if(next.settings.notifications)schedule(false).catch(err=>G.toast('Herinneringen: '+err.message));else if(hadNotifications&&GymNative.available)GymNative.request('notifications',{items:[],requestPermission:false}).catch(err=>G.toast('Meldingen konden niet worden uitgezet: '+err.message));return true;});queue=run.catch(()=>{});return run;}
 };
 function validateState(data){C.upgrade(data);if(data.social===undefined&&window.GymSocialModel)data.social=GymSocialModel.initial();C.validate(data);GymProducts.validateData?.(data);window.GymSocialModel?.validate(data.social);return data;}
 function render(){if(!G.pages[G.ui.page])G.ui.page='today';screen.innerHTML=G.pages[G.ui.page]();const page=G.ui.page;nav.hidden=page==='onboarding';document.body.classList.toggle('onboarding-mode',nav.hidden);let selected='today';if(['planning','planDay','exercise','planImport','aiPlan'].includes(page))selected='planning';if(['stats','body','measurement','photos','photoAdd','photoDetail','photoCompare','usageHistory','productStats'].includes(page))selected='stats';if(page.startsWith('social'))selected='social';nav.innerHTML=[['today','dumbbell','Vandaag'],['planning','calendar-days','Planning'],['social','users','Social'],['stats','chart-no-axes-combined','Progressie']].map(([p,i,t])=>button(icon(i)+`<span>${t}</span>`,p,{},p===selected?'active':'')).join('');if(page==='today'&&G.onboardingChecklist)screen.querySelector('.page-header')?.insertAdjacentHTML('afterend',G.onboardingChecklist());for(const el of document.querySelectorAll('button'))if(!el.textContent.trim()&&!el.hasAttribute('aria-label'))el.setAttribute('aria-label',el.classList.contains('back-button')?'Terug':el.classList.contains('settings-button')?'Instellingen':'Openen');window.lucide?.createIcons({attrs:{width:20,height:20,'stroke-width':1.8}});for(const f of G.afterRender)Promise.resolve().then(f).catch(err=>G.toast(err.message));}
 document.addEventListener('click',async ev=>{const el=ev.target.closest('button');if(!el||el.disabled)return;if(el.dataset.go){let params={};try{params=JSON.parse(el.dataset.params||'{}');}catch{}G.navigate(el.dataset.go,params);}else if(el.dataset.action&&G.actions[el.dataset.action]){try{await G.actions[el.dataset.action](el,ev);}catch(err){G.toast(err.message||'Actie mislukt.');}}});
 document.addEventListener('submit',async ev=>{const form=ev.target;if(!form.matches('form[data-form]'))return;ev.preventDefault();if(form.dataset.busy)return;form.dataset.busy='true';const submit=form.querySelector('button[type=submit]');if(submit)submit.disabled=true;try{await G.forms[form.dataset.form]?.(form);}catch(err){G.formError(form,err.message||'Opslaan mislukt.');}finally{delete form.dataset.busy;if(submit)submit.disabled=false;}});
 G.actions['dialog-cancel']=()=>{dialog.close();confirmCallback=null;};G.actions['dialog-confirm']=async()=>{const fn=confirmCallback;confirmCallback=null;dialog.close();await fn?.();};
 const D=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
 const shortDate=d=>new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
 function dateStrip(){return `<div class="week-control">${action(icon('chevron-left'),'week-shift','data-shift="-7" aria-label="Vorige week"','icon-button')}<span>${dateLabel(C.week(G.ui.date)[0])} — ${dateLabel(C.week(G.ui.date)[6])}</span>${action(icon('chevron-right'),'week-shift','data-shift="7" aria-label="Volgende week"','icon-button')}</div><div class="days">${C.week(G.ui.date).map((d,i)=>`<button data-action="select-date" data-date="${d}" class="day ${d===G.ui.date?'selected':''}" aria-pressed="${d===G.ui.date}"><small>${D[i].slice(0,2)}</small><strong>${Number(d.slice(8))}</strong></button>`).join('')}</div>`;}
 G.actions['week-shift']=el=>{G.ui.date=C.addDays(G.ui.date,Number(el.dataset.shift));render();};G.actions['select-date']=el=>{G.ui.date=el.dataset.date;render();};
 G.pages.today=()=>{const s=C.sessionFor(G.data,G.ui.date),done=s.exercises.filter(e=>e.sets.length&&e.sets.every(x=>x.done)).length;return header(shortDate(G.ui.date),G.data.profile.name?`LET’S WORK, ${G.data.profile.name.split(' ')[0].toUpperCase()}.`:'LET’S WORK.')+dateStrip()+(s.exercises.length?`<section class="session-banner"><span class="eyebrow">${e(s.time||'JOUW TRAINING')}</span><h2>${e(s.name||'WORKOUT').toUpperCase()}</h2><div class="split"><span>${done}/${s.exercises.length} oefeningen klaar</span>${button('Training openen '+icon('arrow-up-right'),'workout',{},'secondary')}</div></section><div class="list">${s.exercises.map(ex=>`<div class="row">${action(ex.sets.every(x=>x.done)?icon('check'):icon('circle'),'exercise-toggle',`data-id="${e(ex.id)}" aria-label="${e(ex.name)} afronden" aria-pressed="${ex.sets.every(x=>x.done)}"`,'icon-button '+(ex.sets.every(x=>x.done)?'complete':''))}<button class="row-link grow" data-go="workout"><strong>${e(ex.name)}</strong><small>${ex.sets.length} sets · ${fmt(ex.sets[0]?.kg||0)} kg${ex.detail?' · '+e(ex.detail):''}</small></button></div>`).join('')}</div>`:empty('Maak ruimte voor training.','Stel je weekplan in of voeg een training voor deze dag toe.',button('Training toevoegen','exercise',{context:'session',exerciseId:null})))+section('DAILY STACK',button('Voorraad '+icon('arrow-up-right'),'inventory',{},'text-button'))+(G.data.products.length?`<div class="list">${G.data.products.slice(0,3).map(p=>`<div class="row"><span class="mini-icon">${icon('package')}</span><div class="grow"><h3>${e(p.name)}</h3><p>${fmt(p.stock)} ${e(p.base==='custom'?p.customLabel:p.base)} over</p></div>${button(icon('plus'),'usage',{productId:p.id},'icon-button')}</div>`).join('')}</div>`:button(icon('plus')+' Product toevoegen','productEdit',{productId:null},'secondary'))+section('HERINNERINGEN',button(icon('plus'),'reminder',{},'icon-button'))+reminderList()+`<details class="details"><summary>${icon('message-square')} Notitie bij je dag</summary><form data-form="day-note" class="fields"><label>Notitie<textarea name="note" maxlength="2000">${e(G.data.notes[G.ui.date]||'')}</textarea></label><button type="submit" class="secondary">Notitie bewaren</button></form></details>`;};
 G.forms['day-note']=async f=>{const note=f.elements.note.value,date=G.ui.date;if(await G.commit(d=>{d.notes[date]=note;}))G.toast('Notitie bewaard.');};
 G.actions['exercise-toggle']=el=>G.commit(d=>{const ex=C.ensureSession(d,G.ui.date).exercises.find(x=>x.id===el.dataset.id);if(ex){const done=!ex.sets.every(s=>s.done);ex.sets.forEach(s=>s.done=done);}});
 G.pages.planning=()=>header('JOUW TRAININGSWEEK','Planning')+`<h2>${e(G.data.plan.name)}</h2><p>Tik op een dag om oefeningen toe te voegen. Je schema herhaalt elke week; afgeronde trainingen blijven bewaard.</p><div class="list">${G.data.plan.days.map((d,i)=>`<button class="weekly-row" data-go="planDay" data-params="${e(JSON.stringify({weekday:i}))}"><span class="weekly-date">${D[i].slice(0,2).toUpperCase()}</span><span class="grow"><strong>${e(d.name||'Nog geen training')}</strong><small>${d.exercises.length?`${d.exercises.length} oefeningen · ${e(d.time)}`:'Training of rustdag instellen'}</small></span>${icon('chevron-right')}</button>`).join('')}</div><section class="panel"><span class="eyebrow">GRATIS · JOUW EIGEN AI</span><h2>Hulp bij je weekplan</h2><p>Kopieer je prompt, gebruik je eigen AI-app en laad het antwoord hier in.</p>${button(icon('sparkles')+' Maak een plan met je eigen AI','aiPlan')}</section>`;
 G.pages.planDay=()=>{const d=G.data.plan.days[G.ui.weekday];return header('WEEKSCHEMA',D[G.ui.weekday],'planning')+`<form data-form="plan-day" class="fields"><label>Naam van je training<input name="name" maxlength="60" value="${e(d.name)}" placeholder="Bijvoorbeeld Push day"></label><label>Tijd<input name="time" type="time" value="${e(d.time)}"></label><button class="primary" type="submit">Dag bewaren</button></form>`+section('OEFENINGEN',button(icon('plus'),'exercise',{context:'plan',exerciseId:null},'icon-button'))+(d.exercises.length?`<div class="list">${d.exercises.map(ex=>`<div class="row"><button class="row-link grow" data-go="exercise" data-params="${e(JSON.stringify({context:'plan',exerciseId:ex.id}))}"><strong>${e(ex.name)}</strong><small>${ex.sets} × ${ex.reps} · ${fmt(ex.kg)} kg</small></button>${action(icon('trash-2'),'plan-exercise-delete',`data-id="${e(ex.id)}" aria-label="${e(ex.name)} verwijderen"`,'icon-button')}</div>`).join('')}</div>`:empty('Nog geen oefeningen.','Voeg oefeningen toe aan deze dag.'))+section('HERINNERINGEN')+`<div class="list">${d.reminders.map(r=>`<div class="row"><div class="grow"><h3>${e(r.text)}</h3><p>${e(r.time)}</p></div>${action(icon('trash-2'),'plan-reminder-delete',`data-id="${e(r.id)}" aria-label="Herinnering verwijderen"`,'icon-button')}</div>`).join('')}</div><form class="fields" data-form="plan-reminder"><label>Wekelijkse herinnering<input name="text" required maxlength="120" placeholder="Bijvoorbeeld: sporttas meenemen"></label><label>Tijd<input name="time" type="time" required value="17:00"></label><button type="submit" class="secondary">Herinnering toevoegen</button></form>`;};
 G.forms['plan-day']=async f=>{const i=G.ui.weekday,name=f.elements.name.value.trim(),time=f.elements.time.value;if(await G.commit(d=>{d.plan.days[i].name=name;d.plan.days[i].time=time;}))G.toast('Weekdag bijgewerkt.');};
 G.actions['plan-exercise-delete']=el=>G.confirm('Oefening verwijderen?','Dit verandert alleen je weekplan. Eerdere trainingen blijven bewaard.',()=>G.commit(d=>{d.plan.days[G.ui.weekday].exercises=d.plan.days[G.ui.weekday].exercises.filter(x=>x.id!==el.dataset.id);}));
 G.actions['plan-reminder-delete']=el=>G.commit(d=>{d.plan.days[G.ui.weekday].reminders=d.plan.days[G.ui.weekday].reminders.filter(x=>x.id!==el.dataset.id);});
 G.forms['plan-reminder']=f=>{const text=f.elements.text.value.trim(),time=f.elements.time.value;if(!text)throw Error('Vul een herinnering in.');return G.commit(d=>{d.plan.days[G.ui.weekday].reminders.push({id:C.uid(),text,time});});};
 function editedExercise(){return G.ui.context==='plan'?G.data.plan.days[G.ui.weekday].exercises.find(e=>e.id===G.ui.exerciseId):C.sessionFor(G.data,G.ui.date).exercises.find(e=>e.id===G.ui.exerciseId);}
 G.pages.exercise=()=>{const ex=editedExercise(),isPlan=G.ui.context==='plan';return header(isPlan?'WEEKSCHEMA':'VANDAAG',ex?'Oefening bewerken':'Oefening toevoegen',isPlan?'planDay':'workout')+`<form data-form="exercise" class="fields"><label>Naam<input name="name" maxlength="80" required value="${e(ex?.name||'')}" placeholder="Bijvoorbeeld Bench press"></label><div class="pair"><label>Sets<input name="sets" inputmode="numeric" value="${isPlan?ex?.sets??3:ex?.sets.length??3}" required></label><label>Herhalingen<input name="reps" inputmode="numeric" value="${isPlan?ex?.reps??8:ex?.sets[0]?.reps??8}" required></label></div><label>Gewicht per set (kg)<input name="kg" inputmode="decimal" value="${isPlan?ex?.kg??0:ex?.sets[0]?.kg??0}" required></label><label>Notitie<input name="detail" maxlength="150" value="${e(ex?.detail||'')}" placeholder="Bijvoorbeeld 90 seconden rust"></label><p class="form-error" role="alert"></p><button type="submit" class="primary">Oefening bewaren</button></form>`;};
 G.forms.exercise=async f=>{const name=f.elements.name.value.trim(),sets=C.parse(f.elements.sets.value),reps=C.parse(f.elements.reps.value),kg=C.parse(f.elements.kg.value),detail=f.elements.detail.value.trim(),isPlan=G.ui.context==='plan',id=G.ui.exerciseId||C.uid();if(!name||!Number.isInteger(sets)||sets<1||sets>30||!Number.isInteger(reps)||reps<1||reps>999||!Number.isFinite(kg)||kg<0)throw Error('Vul een naam, 1–30 sets, 1–999 herhalingen en een geldig gewicht in.');if(await G.commit(d=>{const list=isPlan?d.plan.days[G.ui.weekday].exercises:C.ensureSession(d,G.ui.date).exercises,old=list.find(x=>x.id===id);if(!isPlan&&old?.sets.some(x=>x.done)&&sets<old.sets.length)throw Error('Je kunt afgeronde sets niet via het aantal sets weghalen.');const val=isPlan?{id,name,sets,reps,kg,detail}:{id,name,detail,sets:Array.from({length:sets},(_,i)=>old?.sets[i]?.done?old.sets[i]:{id:old?.sets[i]?.id||C.uid(),kg,reps,done:false})};const index=list.findIndex(x=>x.id===id);if(index<0)list.push(val);else list[index]=val;}))G.navigate(isPlan?'planDay':'workout');};
 G.pages.workout=()=>{const s=C.sessionFor(G.data,G.ui.date);return header(shortDate(G.ui.date),s.name||'Jouw training','today')+(s.exercises.length?s.exercises.map(ex=>`<section class="workout-section"><div class="section-head"><div><h2>${e(ex.name)}</h2>${ex.detail?`<p>${e(ex.detail)}</p>`:''}</div>${button(icon('pencil'),'exercise',{context:'session',exerciseId:ex.id},'icon-button')}</div><div class="set-head"><span>SET</span><span>KG</span><span>REPS</span><span>KLAAR</span></div>${ex.sets.map((set,i)=>`<form class="set-row" data-form="set" data-exercise="${e(ex.id)}" data-set="${e(set.id)}"><span>${i+1}</span><input name="kg" inputmode="decimal" value="${set.kg}" aria-label="${e(ex.name)} set ${i+1} gewicht"><input name="reps" inputmode="numeric" value="${set.reps}" aria-label="${e(ex.name)} set ${i+1} herhalingen"><button type="submit" class="icon-button ${set.done?'complete':''}" aria-pressed="${set.done}" aria-label="${e(ex.name)} set ${i+1} ${set.done?'heropenen':'afronden'}">${icon(set.done?'check':'circle')}</button></form>`).join('')}<div class="split">${action(icon('plus')+' Set','add-set',`data-id="${e(ex.id)}"`,'text-button')}${action('Oefening verwijderen','session-exercise-delete',`data-id="${e(ex.id)}"`,'text-button danger')}</div></section>`).join(''):empty('Nog geen training.','Voeg je eerste oefening toe.'))+button(icon('plus')+' Oefening toevoegen','exercise',{context:'session',exerciseId:null},'secondary');};
 G.forms.set=async f=>{const kg=C.parse(f.elements.kg.value),reps=C.parse(f.elements.reps.value);if(!Number.isFinite(kg)||kg<0||!Number.isInteger(reps)||reps<1||reps>999)throw Error('Gebruik een geldig gewicht en 1–999 herhalingen.');await G.commit(d=>{const ex=C.ensureSession(d,G.ui.date).exercises.find(x=>x.id===f.dataset.exercise),set=ex?.sets.find(x=>x.id===f.dataset.set);if(!set)throw Error('Deze set bestaat niet meer.');const changed=set.kg!==kg||set.reps!==reps;set.kg=kg;set.reps=reps;set.done=changed||!set.done;});};
 G.actions['add-set']=el=>G.commit(d=>{const ex=C.ensureSession(d,G.ui.date).exercises.find(x=>x.id===el.dataset.id);if(ex&&ex.sets.length<30){const prev=ex.sets.at(-1)||{kg:0,reps:8};ex.sets.push({id:C.uid(),kg:prev.kg,reps:prev.reps,done:false});}});
 G.actions['session-exercise-delete']=el=>G.confirm('Oefening verwijderen?','De sets van deze oefening worden uit deze training verwijderd.',()=>G.commit(d=>{const s=C.ensureSession(d,G.ui.date);s.exercises=s.exercises.filter(x=>x.id!==el.dataset.id);}));
 function dayReminders(date){const existing=G.data.reminders.filter(r=>r.date===date),templates=G.data.plan.days[C.weekday(date)].reminders.map(r=>({...r,id:'template:'+r.id,date}));return [...templates.filter(t=>!existing.some(r=>r.templateId===t.id)),...existing];}
 function reminderList(){const list=dayReminders(G.ui.date);return list.length?`<div class="list">${list.map(r=>`<div class="row">${action(icon(r.done?'check':'bell'),'reminder-toggle',`data-id="${e(r.id)}" aria-label="${e(r.text)} afronden"`,'icon-button '+(r.done?'complete':''))}<div class="grow"><h3>${e(r.text)}</h3><p>${e(r.time||'Geen tijd ingesteld')}</p></div>${!r.id.startsWith('template:')?action(icon('trash-2'),'reminder-delete',`data-id="${e(r.id)}" aria-label="Herinnering verwijderen"`,'icon-button'):''}</div>`).join('')}</div>`:'<p class="muted">Geen herinneringen op deze dag.</p>';}
 G.actions['reminder-toggle']=el=>{const ref=dayReminders(G.ui.date).find(r=>r.id===el.dataset.id);return G.commit(d=>{let item=d.reminders.find(r=>r.id===ref.id);if(!item){item={...ref,id:C.uid(),templateId:ref.id};d.reminders.push(item);}item.done=!item.done;});};
 G.actions['reminder-delete']=el=>G.commit(d=>{d.reminders=d.reminders.filter(x=>x.id!==el.dataset.id);});
 G.pages.reminder=()=>header(dateLabel(G.ui.date),'Herinnering toevoegen','today')+`<form class="fields" data-form="reminder"><label>Herinnering<input name="text" maxlength="120" required placeholder="Wat wil je onthouden?"></label><label>Tijd<input name="time" type="time"></label><button class="primary" type="submit">Herinnering bewaren</button></form>`;
 G.forms.reminder=async f=>{const text=f.elements.text.value.trim(),time=f.elements.time.value;if(!text)throw Error('Vul een herinnering in.');if(await G.commit(d=>d.reminders.push({id:C.uid(),date:G.ui.date,text,time,done:false})))G.navigate('today');};
 async function schedule(requestPermission){if(!GymNative.available){if(requestPermission)throw Error('Meldingen werken in de geïnstalleerde iPhone-app.');return;}const items=[];for(let i=0;i<21;i++){const date=C.addDays(C.today(),i),plan=G.data.plan.days[C.weekday(date)];if(plan.exercises.length&&plan.time)items.push({id:'workout-'+date,date,time:plan.time,title:plan.name||'Training',body:'Je training staat klaar.'});for(const r of dayReminders(date))if(r.time&&!r.done)items.push({id:r.id+'-'+date,date,time:r.time,title:'Jouw herinnering',body:r.text});}return GymNative.request('notifications',{items,requestPermission});}
 G.pages.stats=()=>{const rec=C.records(G.data),sessions=Object.entries(G.data.sessions).filter(([,s])=>s.exercises.some(e=>e.sets.some(x=>x.done))).sort((a,b)=>b[0].localeCompare(a[0]));return header('THE WORK ADDS UP','Progressie.')+`<div class="tabs"><button class="active">Training</button>${button('Gewicht','body',{},'')}${button('Producten','productStats',{},'')}</div><div class="metrics"><div><span class="big">${sessions.filter(([d])=>d.startsWith(C.today().slice(0,7))).length}</span><small>trainingen deze maand</small></div><div><span class="big">${rec.length}</span><small>oefeningen met een PR</small></div></div>`+section('PERSOONLIJKE RECORDS')+(rec.length?`<div class="list">${rec.map(r=>`<div class="row"><div class="grow"><h3>${e(r.name)}</h3><p>${dateLabel(r.date)} · ${r.reps} herhalingen</p></div><strong>${fmt(r.kg)} kg</strong></div>`).join('')}</div>`:empty('Je eerste record komt eraan.','Rond een set met gewicht af om hier je PR te zien.',button('Naar je training','workout')))+section('TRAININGSGESCHIEDENIS')+`<div class="list">${sessions.slice(0,30).map(([date,s])=>`<button class="row row-link" data-go="workout" data-params="${e(JSON.stringify({date}))}"><span class="grow"><strong>${e(s.name||'Training')}</strong><small>${dateLabel(date)}</small></span><span>${s.exercises.reduce((n,ex)=>n+ex.sets.filter(x=>x.done).length,0)} sets</span>${icon('chevron-right')}</button>`).join('')}</div>`;};
 const planExample={name:'Mijn week',days:{0:{name:'Push',time:'18:00',exercises:[{name:'Bench press',sets:3,reps:8,kg:0}]},2:{name:'Pull',time:'18:00',exercises:[{name:'Row',sets:3,reps:10,kg:0}]}}};
 G.pages.planImport=()=>header('JOUW EIGEN PLAN','Plan importeren','planning')+`<p>Plak een weekplan als JSON, bijvoorbeeld uit een AI-chat. Dit is een lokale import; de app maakt geen verbinding met AI.</p><details class="details"><summary>${icon('file-json')} Bekijk het formaat</summary><pre>${e(JSON.stringify(planExample,null,2))}</pre><p>Dagen: 0 = maandag, 6 = zondag. De ingevulde gewichten bepaal je zelf.</p></details><form class="fields" data-form="plan-import"><label>Plan (JSON)<textarea name="json" class="code-input" required spellcheck="false" placeholder='{"name":"Mijn week","days":{}}'></textarea></label><p class="form-error" role="alert"></p><button type="submit" class="primary">Plan controleren & importeren</button></form>`;
 G.forms['plan-import']=f=>{const plan=C.importPlan(f.elements.json.value);G.confirm('Weekplan vervangen?',`Je nieuwe plan “${plan.name}” vervangt het weekschema. Gelogde trainingen blijven behouden.`,async()=>{if(await G.commit(d=>{d.plan=plan;}))G.navigate('planning');});};
 G.forms.profile=async f=>{const name=f.elements.name.value.trim(),text=f.elements.height.value.trim(),height=text?C.parse(text):null;if(height!==null&&(!Number.isFinite(height)||height<50||height>300))throw Error('Vul een lengte tussen 50 en 300 cm in.');if(await G.commit(d=>{d.profile={...d.profile,name,heightCm:height};}))G.toast('Profiel bewaard.');};
 G.actions['notifications-toggle']=async()=>{if(G.data.settings.notifications){await GymNative.request('notifications',{items:[],requestPermission:false});await G.commit(d=>d.settings.notifications=false);}else{const result=await schedule(true);if(result?.granted===false)throw Error('Sta meldingen toe via de iPhone-instellingen.');await G.commit(d=>d.settings.notifications=true);}};
 G.actions.export=async()=>{const backup={...G.data,photos:[],exportedAt:new Date().toISOString(),photoBackup:false};await GymStorage.export(backup);G.toast('Gegevensback-up klaargezet. Foto’s blijven apart.');};
 document.addEventListener('change',async ev=>{if(ev.target.id!=='backup-import')return;const file=ev.target.files?.[0];if(!file)return;try{if(file.size>15*1024*1024)throw Error('De back-up is groter dan 15 MB.');const data=validateState(JSON.parse(await file.text()));G.confirm('Gegevens terugzetten?','Dit vervangt je trainingen, planning, voorraad, metingen en lokale groepen. Je bestaande foto’s blijven bewaard.',async()=>{if(await G.commit(d=>{const photos=d.photos;Object.keys(d).forEach(k=>delete d[k]);Object.assign(d,data,{photos});}))G.toast('Gegevens hersteld.');},'Gegevens terugzetten');}catch(err){G.toast(err.message||'Ongeldige back-up.');}ev.target.value='';});
 G.start=async()=>{try{let saved=await GymStorage.load();const previous=JSON.stringify(saved);if(!saved){let legacy;try{legacy=JSON.parse(localStorage.getItem('gympep-state-v1'));}catch{}saved=legacy?C.migrate(legacy):C.initial();}validateState(saved);if(previous!==JSON.stringify(saved))await GymStorage.save(saved);G.data=saved;loaded=true;G.ui.page=saved.settings.onboardingVersion===1?'today':'onboarding';render();if(saved.settings.notifications)schedule(false).catch(()=>{});}catch(err){screen.innerHTML=header('LOKALE OPSLAG','Opslag niet beschikbaar.')+`<p class="form-error">${e(err.message)}</p><p>Je gegevens zijn niet overschreven.</p>${action('Opnieuw proberen','retry')}`;}};
 G.actions.retry=()=>G.start();
})();

