(function(){
 'use strict';
 const C=GymCore,main=document.getElementById('screen'),nav=document.getElementById('nav'),dialog=document.getElementById('dialog'),quickDialog=document.getElementById('quick-dialog'),quickBody=document.getElementById('quick-body');
 let screen=main,quick=null;
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:6}).format(n);
 const icon=n=>`<i data-lucide="${e(n)}" aria-hidden="true"></i>`;
 const dateLabel=d=>C.validDate(d)?new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00')):'—';
 const button=(text,page,params={},className='primary')=>`<button type="button" class="${e(className)}" data-go="${e(page)}" data-params="${e(JSON.stringify(params))}">${text}</button>`;
 const action=(text,name,attrs='',cls='primary')=>`<button type="button" class="${cls}" data-action="${name}" ${attrs}>${text}</button>`;
 const header=(ey,title,back)=>quick?`<header class="quick-header">${quick.router.peek()?action(icon('arrow-left'),'nav-back','aria-label="Terug binnen venster"','quick-back'):''}<h2 id="quick-title" tabindex="-1">${e(title)}</h2>${action(icon('x'),'quick-close','aria-label="Sluiten"','quick-close')}</header>`:`${back?`<div class="back-row">${action(icon('arrow-left')+' Terug','nav-back',`data-fallback="${e(back)}"`,'text-button back-button')}</div>`:''}<header class="page-header"><div class="grow"><span class="eyebrow">${e(ey)}</span><h1>${e(title)}</h1></div>${G.ui.page==='today'?button(icon('settings-2')+'<span>Instellingen</span>','settings',{},'settings-button'):''}</header>`;
 const empty=(title,text,cta='')=>`<div class="empty"><span class="empty-mark">${icon('plus')}</span><h2>${e(title)}</h2><p>${e(text)}</p>${cta}</div>`;
 const section=(title,link='')=>`<div class="section-head"><h2>${e(title)}</h2>${link}</div>`;
 let queue=Promise.resolve(),loaded=false,toastTimer,confirmCallback,savedRoute=null;
 const N=GymNavigation,router=N.create(),drafts=new Map();
 const formKey=f=>[f.dataset.form,f.dataset.exercise||'',f.dataset.set||'',f.dataset.id||''].join(':');
 function captureForms(){
  const route=screen.dataset.route;if(!route)return;
  const saved={forms:{},details:[...screen.querySelectorAll('details')].map(d=>d.open)};
  for(const f of screen.querySelectorAll('form[data-form]')){
   if(f.dataset.busy||f.dataset.form==='savePhoto')continue;
   if(f.dataset.form==='product-save'||f.dataset.form==='usage-save'){const key=f.dataset.form==='product-save'?'productDraft':'usageDraft';saved[key]=G.ui[key]?JSON.parse(JSON.stringify(G.ui[key])):null;continue;}
   const fields=[...f.querySelectorAll('input,textarea,select')].filter(x=>x.name&&x.type!=='file'&&x.type!=='hidden');
   const dirty=fields.some(x=>x.type==='checkbox'?x.checked!==x.defaultChecked:x.tagName==='SELECT'?!x.options[x.selectedIndex]?.defaultSelected:x.value!==x.defaultValue);
   if(dirty)saved.forms[formKey(f)]=fields.map(x=>({name:x.name,value:x.value,checked:x.checked}));
  }
  drafts.set(route,saved);
 }
 function restorePageDraft(){const saved=drafts.get(N.key(G.ui));if(!saved)return;for(const key of ['productDraft','usageDraft'])if(Object.prototype.hasOwnProperty.call(saved,key))G.ui[key]=saved[key]?JSON.parse(JSON.stringify(saved[key])):null;}
 function restoreForms(){const saved=drafts.get(N.key(G.ui));if(!saved)return;for(const f of screen.querySelectorAll('form[data-form]'))for(const field of saved.forms[formKey(f)]||[]){const input=f.elements[field.name];if(!input||input.type==='file')continue;if(input.type==='checkbox')input.checked=field.checked;else if(input.tagName!=='SELECT'||[...input.options].some(o=>o.value===field.value))input.value=field.value;}[...screen.querySelectorAll('details')].forEach((d,i)=>{if(saved.details[i]!==undefined)d.open=saved.details[i];});}
 function focusHeading(){const h=screen.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
 function quickBusy(){return quick&&(quick.submitting>0||quick.pending>0);}
 function quickControls(){if(!quickDialog)return;const busy=!!quickBusy();quickDialog.setAttribute('aria-busy',String(busy));for(const b of quickBody.querySelectorAll('.quick-close,.quick-back'))b.disabled=busy;}
 function sizeQuick(){if(!quickDialog)return;const v=window.visualViewport,height=v?.height||window.innerHeight;quickDialog.style.setProperty('--quick-height',Math.max(160,height-32)+'px');quickDialog.style.setProperty('--quick-top',((v?.offsetTop||0)+height/2)+'px');}
 function focusQuick(){const field=quickBody.querySelector('[data-autofocus]'),target=field||quickBody.querySelector('#quick-title');target?.focus({preventScroll:true});if(field?.select)field.select();}
 function launcherDescriptor(el){if(!el?.getAttribute)return null;return ['data-go','data-params','data-action','data-id','data-page','aria-label'].map(key=>[key,el.getAttribute(key)]);}
 function returnFocus(frame){let target=frame.launcher?.isConnected?frame.launcher:null;if(!target&&frame.launcherKey)target=[...main.querySelectorAll('button')].find(b=>frame.launcherKey.every(([key,value])=>b.getAttribute(key)===value));(target||main.querySelector('h1'))?.focus({preventScroll:true});}
 function closeQuick({discard=false,refresh=true}={}){
  if(!quick)return;if(!discard)captureForms();const frame=quick;quick=null;quickDialog.close();quickBody.innerHTML='';screen=main;Object.assign(G.ui,frame.origin);savedRoute=null;document.body.classList.remove('quick-open');document.body.style.top='';
  if(refresh)render({restore:true});window.scrollTo(0,frame.scroll);if(refresh)returnFocus(frame);
 }
 function previousQuick({discard=false}={}){
  if(!quick)return;if(discard)drafts.delete(N.key(G.ui));else captureForms();const previous=quick.router.back();
  if(!previous){closeQuick({discard:true});return;}Object.assign(G.ui,previous.ui);savedRoute=null;render({restore:true});quickBody.scrollTop=previous.scroll;focusQuick();
 }
 const G=window.Gym={data:C.initial(),ui:{page:'today',date:C.today(),weekday:C.weekday(C.today())},pages:{},actions:{},forms:{},afterRender:[],e,fmt,icon,dateLabel,today:C.today,uid:C.uid,button,header,empty,section,
  toast(message){const el=document.getElementById(quick?'quick-toast':'toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},4200);},
  formError(form,message){let el=form.querySelector('.form-error');if(!el){el=document.createElement('p');el.className='form-error';el.setAttribute('role','alert');form.append(el);}el.textContent=message;},
  confirm(title,text,fn,confirmLabel='Bevestigen'){confirmCallback=fn;dialog.innerHTML=`<h2 id="dialog-title">${e(title)}</h2><p>${e(text)}</p><div class="pair">${action('Annuleren','dialog-cancel','','secondary')}${action(e(confirmLabel),'dialog-confirm','','primary')}</div>`;dialog.showModal();},
  navigate(page,params={},options={}){
   captureForms();const popup=quickDialog&&N.isQuick(page),replace=options.replace||savedRoute===N.key(G.ui);
   if(quick&&!popup)closeQuick({discard:true,refresh:false});
   if(page==='productEdit'&&Object.prototype.hasOwnProperty.call(params,'productId')&&G.ui.page!=='productEdit')G.ui.productDraft=null;
   if(page==='usage'&&G.ui.page!=='usage')G.ui.usageDraft=null;
   const next={...G.ui,...params,page};if(page==='today')next.date=C.today();next.navSection=N.section(page,next);
   if(popup){
    if(!quick){quick={origin:N.snapshot(G.ui),scroll:window.scrollY,launcher:document.activeElement,launcherKey:launcherDescriptor(document.activeElement),router:N.create(),submitting:0,pending:0};document.body.style.top=-quick.scroll+'px';document.body.classList.add('quick-open');screen=quickBody;}
    else quick.router.visit(G.ui,next,{replace,scroll:quickBody.scrollTop});
    Object.assign(G.ui,next);savedRoute=null;render({restore:true});quickBody.scrollTop=0;sizeQuick();if(!quickDialog.open)quickDialog.showModal();focusQuick();return;
   }
   router.visit(G.ui,next,{...options,replace,scroll:window.scrollY});savedRoute=null;Object.assign(G.ui,next);render({restore:true});window.scrollTo(0,0);focusHeading();
  },
  back(fallback='today'){if(quick){if(!quickBusy())previousQuick();return;}captureForms();const previous=router.back();if(!previous){G.navigate(fallback,{}, {reset:true});return;}Object.assign(G.ui,previous.ui);savedRoute=null;render({restore:true});window.scrollTo(0,previous.scroll);focusHeading();},
  finishQuick(fallback,params={}){if(!quick)return G.navigate(fallback,params);Object.assign(G.ui,params);previousQuick({discard:true});},
  closeQuick(){if(quickBusy()){G.toast('Even wachten, je invoer wordt opgeslagen.');return;}closeQuick();},render,
  commit(mutator){const frame=quick;if(frame){frame.pending++;quickControls();}const run=queue.then(async()=>{if(!loaded){G.toast('Je gegevens zijn nog niet beschikbaar.');return false;}const next=JSON.parse(JSON.stringify(G.data)),hadNotifications=G.data.settings.notifications;try{await mutator(next);validateState(next);await GymStorage.save(next);}catch(err){G.toast(err.message||'Opslaan mislukt. Je vorige gegevens zijn behouden.');return false;}G.data=next;if(screen.querySelector('form[data-busy]'))savedRoute=N.key(G.ui);try{captureForms();render({restore:true});}catch(err){G.toast('Je gegevens zijn bewaard. Open dit scherm opnieuw.');}if(next.settings.notifications)schedule(false).catch(err=>G.toast('Herinneringen: '+err.message));else if(hadNotifications&&GymNative.available)GymNative.request('notifications',{items:[],requestPermission:false}).catch(err=>G.toast('Meldingen konden niet worden uitgezet: '+err.message));return true;});queue=run.catch(()=>{});return run.finally(()=>{if(frame){frame.pending--;quickControls();}});}
 };
 function validateState(data){C.upgrade(data);if(data.social===undefined&&window.GymSocialModel)data.social=GymSocialModel.initial();C.validate(data);GymProducts.validateData?.(data);window.GymSocialModel?.upgrade?.(data.social);window.GymSocialModel?.validate(data.social);return data;}
 function render(options={}){if(!G.pages[G.ui.page])G.ui.page='today';if(options.restore)restorePageDraft();screen.innerHTML=G.pages[G.ui.page]();screen.dataset.route=N.key(G.ui);const page=quick?quick.origin.page:G.ui.page;nav.hidden=page==='onboarding';document.body.classList.toggle('onboarding-mode',nav.hidden);const selected=N.section(page,quick?quick.origin:G.ui);if(!quick)nav.innerHTML=N.tabs.map(([p,i,t])=>`<button type="button" data-action="nav-tab" data-page="${p}" class="${p===selected?'active':''}" ${p===selected?'aria-current="page"':''}>${icon(i)}<span>${t}</span></button>`).join('');if(!quick&&page==='today'&&G.onboardingChecklist)screen.insertAdjacentHTML('beforeend',G.onboardingChecklist());if(options.restore)restoreForms();else drafts.delete(N.key(G.ui));for(const el of document.querySelectorAll('button'))if(!el.textContent.trim()&&!el.hasAttribute('aria-label'))el.setAttribute('aria-label','Openen');quickControls();window.lucide?.createIcons({attrs:{width:20,height:20,'stroke-width':1.8}});for(const f of G.afterRender)Promise.resolve().then(f).catch(err=>G.toast(err.message));}
 const subnav=(label,items,active)=>`<div class="section-tabs" role="group" aria-label="${label}">${items.map(([page,text])=>`<button type="button" data-go="${page}" class="${active===page?'active':''}" ${active===page?'aria-current="page"':''}>${text}</button>`).join('')}</div>`;
 G.trainingTabs=active=>subnav('Training bekijken',[['workout','Training'],['planning','Weekplan']],active);
 G.progressTabs=active=>subnav('Progressie bekijken',[['stats','Kracht'],['body','Gewicht'],['photos','Foto’s']],active);
 G.productTabs=active=>subnav('Producten bekijken',[['inventory','Voorraad'],['productStats','Gebruik']],active);
 G.actions['nav-back']=el=>G.back(el.dataset.fallback);
 G.actions['quick-close']=()=>G.closeQuick();
 if(quickDialog){
  quickDialog.addEventListener('cancel',ev=>{ev.preventDefault();G.closeQuick();});
  quickDialog.addEventListener('click',ev=>{if(ev.target!==quickDialog)return;const r=quickDialog.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)G.closeQuick();});
  window.visualViewport?.addEventListener('resize',()=>{sizeQuick();if(quickBody.contains(document.activeElement))document.activeElement.scrollIntoView?.({block:'nearest'});});
  window.visualViewport?.addEventListener('scroll',sizeQuick);
 }
 G.actions['nav-tab']=el=>G.navigate(el.dataset.page,el.dataset.page==='workout'?{date:C.today()}:{},{reset:true});
 document.addEventListener('click',async ev=>{const el=ev.target.closest('button');if(!el||el.disabled||quickBusy())return;if(el.dataset.go){let params={};try{params=JSON.parse(el.dataset.params||'{}');}catch{}G.navigate(el.dataset.go,params);}else if(el.dataset.action&&G.actions[el.dataset.action]){try{await G.actions[el.dataset.action](el,ev);}catch(err){G.toast(err.message||'Actie mislukt.');}}});
 document.addEventListener('submit',async ev=>{const form=ev.target;if(!form.matches('form[data-form]'))return;ev.preventDefault();if(form.dataset.busy||quickBusy())return;const frame=quick;if(frame){frame.submitting++;quickControls();}form.dataset.busy='true';const submit=form.querySelector('button[type=submit]');if(submit)submit.disabled=true;try{await G.forms[form.dataset.form]?.(form);}catch(err){G.formError(form,err.message||'Opslaan mislukt.');}finally{delete form.dataset.busy;if(submit)submit.disabled=false;savedRoute=null;if(frame){frame.submitting--;quickControls();}}});
 G.actions['dialog-cancel']=()=>{dialog.close();confirmCallback=null;};G.actions['dialog-confirm']=async()=>{const fn=confirmCallback;confirmCallback=null;dialog.close();await fn?.();};
 const D=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
 const shortDate=d=>new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
 function dateStrip(){return `<div class="week-control">${action(icon('chevron-left'),'week-shift','data-shift="-7" aria-label="Vorige week"','icon-button')}<span>${dateLabel(C.week(G.ui.date)[0])} — ${dateLabel(C.week(G.ui.date)[6])}</span>${action(icon('chevron-right'),'week-shift','data-shift="7" aria-label="Volgende week"','icon-button')}</div><div class="days">${C.week(G.ui.date).map((d,i)=>`<button data-action="select-date" data-date="${d}" class="day ${d===G.ui.date?'selected':''}" aria-pressed="${d===G.ui.date}"><small>${D[i].slice(0,2)}</small><strong>${Number(d.slice(8))}</strong></button>`).join('')}</div>`;}
 G.actions['week-shift']=el=>{G.ui.date=C.addDays(G.ui.date,Number(el.dataset.shift));render();};G.actions['select-date']=el=>{G.ui.date=el.dataset.date;render();};
 G.pages.today=()=>{
  const date=C.today(),s=C.sessionFor(G.data,date),sets=s.exercises.flatMap(ex=>ex.sets),done=sets.filter(x=>x.done).length;
  const title=s.exercises.length?(s.name||'Jouw training'):'Klaar om te trainen?';
  const products=G.data.products.slice(0,3);
  return header(shortDate(date),'Vandaag')+`<section class="today-training"><div class="split"><span class="eyebrow">JOUW TRAINING</span><span class="task-icon">${icon('dumbbell')}</span></div><h2>${e(title)}</h2><p>${sets.length?`${done} van ${sets.length} sets opgeslagen · ${s.exercises.length} ${s.exercises.length===1?'oefening':'oefeningen'}`:'Voeg je oefeningen toe en houd iedere set bij.'}</p>${sets.length?`<div class="track"><span style="width:${done/sets.length*100}%"></span></div>`:''}${button((done===sets.length&&sets.length?'Training bekijken':done?'Verder trainen':'Training openen')+' '+icon('arrow-right'),'workout',{date})}${button('Weekplan bekijken','planning',{},'text-button')}</section>`+
  section('Producten',button('Alle producten '+icon('chevron-right'),'inventory',{},'text-button'))+(products.length?`<div class="home-products">${products.map(p=>`<div class="home-product"><div><h3>${e(p.name)}</h3><p>${fmt(p.stock)} ${e(p.base==='custom'?p.customLabel:p.base)} over</p></div>${button('Gebruik invoeren','usage',{productId:p.id},'secondary compact-button')}</div>`).join('')}</div>`:`<div class="home-empty"><p>Houd je voorraad en gebruik bij, in jouw eigen eenheid.</p>${button(icon('plus')+' Product toevoegen','productEdit',{productId:null},'secondary')}</div>`)+
  section('Gewicht en foto’s')+`<div class="quick-actions">${button(icon('scale')+'<span>Gewicht invoeren</span>','measurement',{measurementId:''},'quick-action')}${button(icon('camera')+'<span>Foto toevoegen</span>','photoAdd',{},'quick-action')}</div>`+
  `<details class="details"><summary>${icon('bell')} Herinneringen voor vandaag</summary>${reminderList()}${button(icon('plus')+' Herinnering toevoegen','reminder',{},'secondary')}</details><details class="details"><summary>${icon('message-square')} Notitie bij je dag</summary><form data-form="day-note" class="fields"><label>Notitie<textarea name="note" maxlength="2000">${e(G.data.notes[date]||'')}</textarea></label><button type="submit" class="secondary">Notitie bewaren</button></form></details>`;
 };
 G.forms['day-note']=async f=>{const note=f.elements.note.value,date=G.ui.date;if(await G.commit(d=>{d.notes[date]=note;}))G.toast('Notitie bewaard.');};
 G.actions['exercise-toggle']=el=>G.commit(d=>{const ex=C.ensureSession(d,G.ui.date).exercises.find(x=>x.id===el.dataset.id);if(ex){const done=!ex.sets.every(s=>s.done);ex.sets.forEach(s=>s.done=done);}});
 G.pages.planning=()=>header('HERHAALT ELKE WEEK','Trainen')+G.trainingTabs('planning')+`<div class="section-intro"><h2>Je weekplan</h2><p>Kies een dag en voeg oefeningen toe. Je training voor vandaag verschijnt vanzelf onder Training.</p></div><div class="list week-plan">${G.data.plan.days.map((d,i)=>`<button class="weekly-row" data-go="planDay" data-params="${e(JSON.stringify({weekday:i}))}"><span class="grow"><strong>${D[i]}</strong><small>${d.exercises.length?`${e(d.name||'Training')} · ${d.exercises.length} ${d.exercises.length===1?'oefening':'oefeningen'}${d.time?' · '+e(d.time):''}`:e(d.name||'Nog geen training gepland')}</small></span>${icon('chevron-right')}</button>`).join('')}</div><section class="panel"><span class="eyebrow">GRATIS · JOUW EIGEN AI</span><h2>Hulp bij je weekplan</h2><p>Kopieer je wensen naar je eigen AI en plak het antwoord hier terug.</p>${button(icon('sparkles')+' Weekplan maken met AI','aiPlan',{},'secondary')}</section>`;
 G.pages.planDay=()=>{const d=G.data.plan.days[G.ui.weekday];return header('WEEKSCHEMA',D[G.ui.weekday],'planning')+`<form data-form="plan-day" class="fields"><label>Naam van je training<input name="name" maxlength="60" value="${e(d.name)}" placeholder="Bijvoorbeeld Push day"></label><label>Tijd<input name="time" type="time" value="${e(d.time)}"></label><button class="primary" type="submit">Dag bewaren</button></form>`+section('Oefeningen',button(icon('plus')+' Oefening toevoegen','exercise',{context:'plan',exerciseId:null},'text-button'))+(d.exercises.length?`<div class="list">${d.exercises.map(ex=>`<div class="row"><button class="row-link grow" data-go="exercise" data-params="${e(JSON.stringify({context:'plan',exerciseId:ex.id}))}"><strong>${e(ex.name)}</strong><small>${ex.sets} × ${ex.reps} · ${fmt(ex.kg)} kg</small></button>${action(icon('trash-2'),'plan-exercise-delete',`data-id="${e(ex.id)}" aria-label="${e(ex.name)} verwijderen"`,'icon-button')}</div>`).join('')}</div>`:empty('Nog geen oefeningen.','Voeg oefeningen toe aan deze dag.'))+section('HERINNERINGEN')+`<div class="list">${d.reminders.map(r=>`<div class="row"><div class="grow"><h3>${e(r.text)}</h3><p>${e(r.time)}</p></div>${action(icon('trash-2'),'plan-reminder-delete',`data-id="${e(r.id)}" aria-label="Herinnering verwijderen"`,'icon-button')}</div>`).join('')}</div><form class="fields" data-form="plan-reminder"><label>Wekelijkse herinnering<input name="text" required maxlength="120" placeholder="Bijvoorbeeld: sporttas meenemen"></label><label>Tijd<input name="time" type="time" required value="17:00"></label><button type="submit" class="secondary">Herinnering toevoegen</button></form>`;};
 G.forms['plan-day']=async f=>{const i=G.ui.weekday,name=f.elements.name.value.trim(),time=f.elements.time.value;if(await G.commit(d=>{d.plan.days[i].name=name;d.plan.days[i].time=time;}))G.toast('Weekdag bijgewerkt.');};
 G.actions['plan-exercise-delete']=el=>G.confirm('Oefening verwijderen?','Dit verandert alleen je weekplan. Eerdere trainingen blijven bewaard.',()=>G.commit(d=>{d.plan.days[G.ui.weekday].exercises=d.plan.days[G.ui.weekday].exercises.filter(x=>x.id!==el.dataset.id);}));
 G.actions['plan-reminder-delete']=el=>G.commit(d=>{d.plan.days[G.ui.weekday].reminders=d.plan.days[G.ui.weekday].reminders.filter(x=>x.id!==el.dataset.id);});
 G.forms['plan-reminder']=f=>{const text=f.elements.text.value.trim(),time=f.elements.time.value;if(!text)throw Error('Vul een herinnering in.');return G.commit(d=>{d.plan.days[G.ui.weekday].reminders.push({id:C.uid(),text,time});});};
 function editedExercise(){return G.ui.context==='plan'?G.data.plan.days[G.ui.weekday].exercises.find(e=>e.id===G.ui.exerciseId):C.sessionFor(G.data,G.ui.date).exercises.find(e=>e.id===G.ui.exerciseId);}
 G.pages.exercise=()=>{const ex=editedExercise(),isPlan=G.ui.context==='plan';return header(isPlan?'WEEKSCHEMA':'VANDAAG',ex?'Oefening bewerken':'Oefening toevoegen',isPlan?'planDay':'workout')+`<form data-form="exercise" class="fields"><label>Naam<input name="name" maxlength="80" required value="${e(ex?.name||'')}" placeholder="Bijvoorbeeld Bench press"></label><div class="pair"><label>Sets<input name="sets" inputmode="numeric" value="${isPlan?ex?.sets??3:ex?.sets.length??3}" required></label><label>Herhalingen<input name="reps" inputmode="numeric" value="${isPlan?ex?.reps??8:ex?.sets[0]?.reps??8}" required></label></div><label>Gewicht per set (kg)<input name="kg" inputmode="decimal" value="${isPlan?ex?.kg??0:ex?.sets[0]?.kg??0}" required></label><label>Notitie<input name="detail" maxlength="150" value="${e(ex?.detail||'')}" placeholder="Bijvoorbeeld 90 seconden rust"></label><p class="form-error" role="alert"></p><button type="submit" class="primary">Oefening bewaren</button></form>`;};
 G.forms.exercise=async f=>{const name=f.elements.name.value.trim(),sets=C.parse(f.elements.sets.value),reps=C.parse(f.elements.reps.value),kg=C.parse(f.elements.kg.value),detail=f.elements.detail.value.trim(),isPlan=G.ui.context==='plan',date=G.ui.date,weekday=G.ui.weekday,id=G.ui.exerciseId||C.uid();if(!name||!Number.isInteger(sets)||sets<1||sets>30||!Number.isInteger(reps)||reps<1||reps>999||!Number.isFinite(kg)||kg<0)throw Error('Vul een naam, 1–30 sets, 1–999 herhalingen en een geldig gewicht in.');if(await G.commit(d=>{const list=isPlan?d.plan.days[weekday].exercises:C.ensureSession(d,date).exercises,old=list.find(x=>x.id===id);if(!isPlan&&old?.sets.some(x=>x.done)&&sets<old.sets.length)throw Error('Je kunt afgeronde sets niet via het aantal sets weghalen.');const val=isPlan?{id,name,sets,reps,kg,detail}:{id,name,detail,sets:Array.from({length:sets},(_,i)=>old?.sets[i]?.done?old.sets[i]:{id:old?.sets[i]?.id||C.uid(),kg,reps,done:false})};const index=list.findIndex(x=>x.id===id);if(index<0)list.push(val);else list[index]=val;})){G.finishQuick(isPlan?'planDay':'workout',isPlan?{weekday}:{date});G.toast('Oefening opgeslagen.');}};
 G.pages.workout=()=>{const s=C.sessionFor(G.data,G.ui.date),done=s.exercises.flatMap(x=>x.sets).filter(x=>x.done).length,total=s.exercises.reduce((n,x)=>n+x.sets.length,0);return header('SETS EN GEWICHTEN','Trainen',router.peek()?.ui.page==='stats'?'stats':null)+G.trainingTabs('workout')+`<div class="training-date"><label for="training-date">Training op<input id="training-date" type="date" value="${G.ui.date}" aria-label="Datum van je training"></label>${G.ui.date!==C.today()?action('Naar vandaag','training-today','','secondary compact-button'):''}</div>${G.ui.date!==C.today()?`<p class="history-notice">Je bekijkt ${e(shortDate(G.ui.date))}. Invoer wordt op deze datum opgeslagen.</p>`:''}`+(s.exercises.length?`<div class="session-summary"><h2>${e(s.name||'Jouw training')}</h2><span>${done} van ${total} sets opgeslagen</span></div><p class="workout-hint">Vul kg en herhalingen in. Tik op Bewaar na iedere set.</p>`+s.exercises.map(ex=>`<section class="workout-section"><div class="section-head"><div><h2>${e(ex.name)}</h2>${ex.detail?`<p>${e(ex.detail)}</p>`:''}</div>${button('Bewerken','exercise',{context:'session',exerciseId:ex.id},'text-button')}</div><div class="set-head"><span>Set</span><span>Kg</span><span>Herhalingen</span><span>Opslaan</span></div>${ex.sets.map((set,i)=>`<form class="set-row" data-form="set" data-exercise="${e(ex.id)}" data-set="${e(set.id)}"><span>${i+1}</span><input name="kg" inputmode="decimal" value="${set.kg}" aria-label="${e(ex.name)} set ${i+1} gewicht"><input name="reps" inputmode="numeric" value="${set.reps}" aria-label="${e(ex.name)} set ${i+1} herhalingen"><button type="submit" class="set-save ${set.done?'complete':''}" aria-pressed="${set.done}" aria-label="${e(ex.name)} set ${i+1} ${set.done?'opgeslagen':'bewaren'}">${icon(set.done?'check':'plus')}<span>${set.done?'Bewaard':'Bewaar'}</span></button></form>`).join('')}<div class="split">${action(icon('plus')+' Set toevoegen','add-set',`data-id="${e(ex.id)}"`,'text-button')}<details class="exercise-options"><summary>Meer</summary><div class="exercise-menu">${action('Opgeslagen sets ongedaan maken','session-sets-reset',`data-id="${e(ex.id)}"`,'text-button')}${action('Oefening verwijderen','session-exercise-delete',`data-id="${e(ex.id)}"`,'text-button danger')}</div></details></div></section>`).join(''):empty('Voeg je eerste oefening toe.','Daarna kun je per set je gewicht en herhalingen bewaren.',button(icon('plus')+' Oefening toevoegen','exercise',{context:'session',exerciseId:null})))+(s.exercises.length?button(icon('plus')+' Oefening toevoegen','exercise',{context:'session',exerciseId:null},'secondary'):'');};
 G.actions['training-today']=()=>G.navigate('workout',{date:C.today()},{replace:true});
 function updateSetButton(form){const button=form.querySelector('button[type=submit]');if(!button)return;const changed=['kg','reps'].some(name=>form.elements[name].value!==form.elements[name].defaultValue),saved=button.getAttribute('aria-pressed')==='true';button.classList.toggle('unsaved',changed);button.querySelector('span').textContent=saved&&!changed?'Bewaard':'Bewaar';button.setAttribute('aria-label',form.elements.kg.getAttribute('aria-label').replace(/ gewicht$/,'')+(saved&&!changed?' opgeslagen':' bewaren'));}
 document.addEventListener('input',ev=>{const form=ev.target.closest('form[data-form="set"]');if(form)updateSetButton(form);});
 G.afterRender.push(()=>screen.querySelectorAll('form[data-form="set"]').forEach(updateSetButton));
 G.actions['session-sets-reset']=el=>{const date=G.ui.date,id=el.dataset.id;G.confirm('Sets weer openzetten?','De gewichten en herhalingen blijven staan. Deze sets tellen pas opnieuw mee bij je progressie als je ze bewaart.',()=>G.commit(d=>{const ex=C.ensureSession(d,date).exercises.find(x=>x.id===id);if(ex)ex.sets.forEach(set=>set.done=false);}),'Sets openzetten');};
 document.addEventListener('change',ev=>{if(ev.target.id==='training-date'&&C.validDate(ev.target.value))G.navigate('workout',{date:ev.target.value},{replace:true});});
 G.forms.set=async f=>{const kg=C.parse(f.elements.kg.value),reps=C.parse(f.elements.reps.value);if(!Number.isFinite(kg)||kg<0||!Number.isInteger(reps)||reps<1||reps>999)throw Error('Gebruik een geldig gewicht en 1–999 herhalingen.');const date=G.ui.date;await G.commit(d=>{const ex=C.ensureSession(d,date).exercises.find(x=>x.id===f.dataset.exercise),set=ex?.sets.find(x=>x.id===f.dataset.set);if(!set)throw Error('Deze set bestaat niet meer.');set.kg=kg;set.reps=reps;set.done=true;});};
 G.actions['add-set']=el=>G.commit(d=>{const ex=C.ensureSession(d,G.ui.date).exercises.find(x=>x.id===el.dataset.id);if(ex&&ex.sets.length<30){const prev=ex.sets.at(-1)||{kg:0,reps:8};ex.sets.push({id:C.uid(),kg:prev.kg,reps:prev.reps,done:false});}});
 G.actions['session-exercise-delete']=el=>G.confirm('Oefening verwijderen?','De sets van deze oefening worden uit deze training verwijderd.',()=>G.commit(d=>{const s=C.ensureSession(d,G.ui.date);s.exercises=s.exercises.filter(x=>x.id!==el.dataset.id);}));
 function dayReminders(date){const existing=G.data.reminders.filter(r=>r.date===date),templates=G.data.plan.days[C.weekday(date)].reminders.map(r=>({...r,id:'template:'+r.id,date}));return [...templates.filter(t=>!existing.some(r=>r.templateId===t.id)),...existing];}
 function reminderList(){const list=dayReminders(G.ui.date);return list.length?`<div class="list">${list.map(r=>`<div class="row">${action(icon(r.done?'check':'bell'),'reminder-toggle',`data-id="${e(r.id)}" aria-label="${e(r.text)} afronden"`,'icon-button '+(r.done?'complete':''))}<div class="grow"><h3>${e(r.text)}</h3><p>${e(r.time||'Geen tijd ingesteld')}</p></div>${!r.id.startsWith('template:')?action(icon('trash-2'),'reminder-delete',`data-id="${e(r.id)}" aria-label="Herinnering verwijderen"`,'icon-button'):''}</div>`).join('')}</div>`:'<p class="muted">Geen herinneringen op deze dag.</p>';}
 G.actions['reminder-toggle']=el=>{const ref=dayReminders(G.ui.date).find(r=>r.id===el.dataset.id);return G.commit(d=>{let item=d.reminders.find(r=>r.id===ref.id);if(!item){item={...ref,id:C.uid(),templateId:ref.id};d.reminders.push(item);}item.done=!item.done;});};
 G.actions['reminder-delete']=el=>G.commit(d=>{d.reminders=d.reminders.filter(x=>x.id!==el.dataset.id);});
 G.pages.reminder=()=>header(dateLabel(G.ui.date),'Herinnering toevoegen','today')+`<form class="fields" data-form="reminder"><label>Herinnering<input name="text" maxlength="120" required placeholder="Wat wil je onthouden?"></label><label>Tijd<input name="time" type="time"></label><button class="primary" type="submit">Herinnering bewaren</button></form>`;
 G.forms.reminder=async f=>{const text=f.elements.text.value.trim(),time=f.elements.time.value;if(!text)throw Error('Vul een herinnering in.');if(await G.commit(d=>d.reminders.push({id:C.uid(),date:G.ui.date,text,time,done:false})))G.finishQuick('today');};
 async function schedule(requestPermission){if(!GymNative.available){if(requestPermission)throw Error('Meldingen werken in de geïnstalleerde iPhone-app.');return;}const items=[];for(let i=0;i<21;i++){const date=C.addDays(C.today(),i),plan=G.data.plan.days[C.weekday(date)];if(plan.exercises.length&&plan.time)items.push({id:'workout-'+date,date,time:plan.time,title:plan.name||'Training',body:'Je training staat klaar.'});for(const r of dayReminders(date))if(r.time&&!r.done)items.push({id:r.id+'-'+date,date,time:r.time,title:'Jouw herinnering',body:r.text});}return GymNative.request('notifications',{items,requestPermission});}
 G.pages.stats=()=>{const rec=C.records(G.data),sessions=Object.entries(G.data.sessions).filter(([,s])=>s.exercises.some(e=>e.sets.some(x=>x.done))).sort((a,b)=>b[0].localeCompare(a[0]));return header('JOUW RESULTATEN','Progressie')+G.progressTabs('stats')+`<div class="section-intro"><h2>Je kracht en trainingen</h2><p>Je persoonlijke records en afgeronde sets, op één plek.</p></div><div class="metrics"><div><span class="big">${sessions.filter(([d])=>d.startsWith(C.today().slice(0,7))).length}</span><small>trainingen deze maand</small></div><div><span class="big">${rec.length}</span><small>oefeningen met een PR</small></div></div>`+section('PERSOONLIJKE RECORDS')+(rec.length?`<div class="list">${rec.map(r=>`<div class="row"><div class="grow"><h3>${e(r.name)}</h3><p>${dateLabel(r.date)} · ${r.reps} herhalingen</p></div><strong>${fmt(r.kg)} kg</strong></div>`).join('')}</div>`:empty('Je eerste record komt eraan.','Rond een set met gewicht af om hier je PR te zien.',button('Naar je training','workout')))+section('TRAININGSGESCHIEDENIS')+`<div class="list">${sessions.slice(0,30).map(([date,s])=>`<button class="row row-link" data-go="workout" data-params="${e(JSON.stringify({date}))}"><span class="grow"><strong>${e(s.name||'Training')}</strong><small>${dateLabel(date)}</small></span><span>${s.exercises.reduce((n,ex)=>n+ex.sets.filter(x=>x.done).length,0)} sets</span>${icon('chevron-right')}</button>`).join('')}</div>`;};
 const planExample={name:'Mijn week',days:{0:{name:'Push',time:'18:00',exercises:[{name:'Bench press',sets:3,reps:8,kg:0}]},2:{name:'Pull',time:'18:00',exercises:[{name:'Row',sets:3,reps:10,kg:0}]}}};
 G.pages.planImport=()=>header('JOUW EIGEN PLAN','Plan importeren','planning')+`<p>Plak een weekplan als JSON, bijvoorbeeld uit een AI-chat. Dit is een lokale import; de app maakt geen verbinding met AI.</p><details class="details"><summary>${icon('file-json')} Bekijk het formaat</summary><pre>${e(JSON.stringify(planExample,null,2))}</pre><p>Dagen: 0 = maandag, 6 = zondag. De ingevulde gewichten bepaal je zelf.</p></details><form class="fields" data-form="plan-import"><label>Plan (JSON)<textarea name="json" class="code-input" required spellcheck="false" placeholder='{"name":"Mijn week","days":{}}'></textarea></label><p class="form-error" role="alert"></p><button type="submit" class="primary">Plan controleren & importeren</button></form>`;
 G.forms['plan-import']=f=>{const plan=C.importPlan(f.elements.json.value);G.confirm('Weekplan vervangen?',`Je nieuwe plan “${plan.name}” vervangt het weekschema. Gelogde trainingen blijven behouden.`,async()=>{if(await G.commit(d=>{d.plan=plan;}))G.navigate('planning');});};
 G.forms.profile=async f=>{const name=f.elements.name.value.trim(),text=f.elements.height.value.trim(),height=text?C.parse(text):null;if(height!==null&&(!Number.isFinite(height)||height<50||height>300))throw Error('Vul een lengte tussen 50 en 300 cm in.');if(await G.commit(d=>{d.profile={...d.profile,name,heightCm:height};}))G.toast('Profiel bewaard.');};
 G.actions['notifications-toggle']=async()=>{if(G.data.settings.notifications){await GymNative.request('notifications',{items:[],requestPermission:false});await G.commit(d=>d.settings.notifications=false);}else{const result=await schedule(true);if(result?.granted===false)throw Error('Sta meldingen toe via de iPhone-instellingen.');await G.commit(d=>d.settings.notifications=true);}};
 G.actions.export=async()=>{const backup={...G.data,photos:[],exportedAt:new Date().toISOString(),photoBackup:false};await GymStorage.export(backup);G.toast('Gegevensback-up klaargezet. Foto’s blijven apart.');};
 document.addEventListener('change',async ev=>{if(ev.target.id!=='backup-import')return;const file=ev.target.files?.[0];if(!file)return;try{if(file.size>15*1024*1024)throw Error('De back-up is groter dan 15 MB.');const data=validateState(JSON.parse(await file.text()));G.confirm('Gegevens terugzetten?','Dit vervangt je trainingen, planning, voorraad, metingen en lokale groepen. Je bestaande foto’s blijven bewaard.',async()=>{if(await G.commit(d=>{const photos=d.photos;Object.keys(d).forEach(k=>delete d[k]);Object.assign(d,data,{photos});}))G.toast('Gegevens hersteld.');},'Gegevens terugzetten');}catch(err){G.toast(err.message||'Ongeldige back-up.');}ev.target.value='';});
 G.start=async()=>{try{let saved=await GymStorage.load();const previous=JSON.stringify(saved);if(!saved){let legacy;try{legacy=JSON.parse(localStorage.getItem('gympep-state-v1'));}catch{}saved=legacy?C.migrate(legacy):C.initial();}validateState(saved);if(previous!==JSON.stringify(saved))await GymStorage.save(saved);G.data=saved;loaded=true;G.ui.page=saved.settings.onboardingVersion===1?'today':'onboarding';render();if(saved.settings.notifications)schedule(false).catch(()=>{});}catch(err){screen.innerHTML=header('LOKALE OPSLAG','Opslag niet beschikbaar.')+`<p class="form-error">${e(err.message)}</p><p>Je gegevens zijn niet overschreven.</p>${action('Opnieuw proberen','retry')}`;}};
 G.actions.retry=()=>G.start();
})();

