(function () {
 'use strict';
 const G=window.Gym, e=G.e, icon=G.icon, button=G.button;
 const action=(label,name,attrs='',className='secondary')=>`<button type="button" class="${className}" data-action="${name}" ${attrs}>${label}</button>`;
 G.isPremium=()=>G.data.settings.premiumPreview===true;
 G.copyText=async text=>{
  if(typeof text!=='string'||!text.trim()||new TextEncoder().encode(text).length>100000)throw Error('Deze tekst kan niet worden gekopieerd.');
  if(GymNative.available){await GymNative.request('copyText',{text});return true;}
  if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return true;}catch{}}
  const area=document.createElement('textarea');area.value=text;area.setAttribute('aria-label','Tekst om te kopiëren');area.style.cssText='position:fixed;top:0;left:0;width:1px;height:1px;opacity:0';document.body.append(area);area.focus();area.select();area.setSelectionRange(0,text.length);
  let copied=false;try{copied=document.execCommand('copy');}finally{area.remove();}
  if(!copied)throw Error('Automatisch kopiëren lukt niet. Selecteer de zichtbare tekst en kies Kopieer.');return true;
 };
 G.pages.settings=()=>G.header('JOUW APP','Instellingen','today')+`
  <section class="account-status"><span class="mini-icon">${icon(G.isPremium()?'crown':'user-round')}</span><div class="grow"><h2>${G.isPremium()?'Premium · teststand':'Gratis versie'}</h2><p>${G.isPremium()?'Geen aankoop. Je kunt dit altijd weer uitzetten.':'Je eigen gegevens, zonder inloggen.'}</p></div></section>
  ${button(G.isPremium()?'Premium-test beheren':'Premium bekijken','premium',{},'secondary')}
  <details class="details"><summary>${icon('user-round')} Mijn profiel</summary><form class="fields" data-form="profile"><label>Naam<input name="name" maxlength="80" value="${e(G.data.profile.name)}" placeholder="Hoe mogen we je noemen?"></label><label>Lengte (cm) · optioneel<input name="height" inputmode="decimal" value="${G.data.profile.heightCm??''}" placeholder="Bijvoorbeeld 182"></label><button type="submit" class="secondary">Profiel bewaren</button></form></details>
  ${G.section('HULP & UITLEG')}${button(icon('circle-help')+' Zo werkt de app','help',{},'secondary')}${action(icon('play')+' Introductie opnieuw bekijken','onboarding-replay')}
  ${G.section('PRIVACY')}<section class="privacy-callout"><span class="mini-icon">${icon('shield-check')}</span><div><h2>Jouw foto’s. Jouw toestel.</h2><p>${GymNative.available?'Foto’s worden uitsluitend in deze app op je iPhone bewaard.':'Foto’s worden uitsluitend in deze browser bewaard.'} Deze app stuurt ze nooit naar een server. Je foto’s worden ook niet in AI-prompts of gegevensback-ups opgenomen.</p>${button('Lees hoe opslag werkt','privacy',{},'text-button')}</div></section>
  ${G.section('HERINNERINGEN')}<div class="row"><div class="grow"><h3>Lokale meldingen</h3><p>${G.data.settings.notifications?'Ingeschakeld op deze iPhone.':'Ontvang een melding voor je ingeplande training.'}</p></div>${action(G.data.settings.notifications?'Uitzetten':'Aanzetten','notifications-toggle','','text-button')}</div>
  ${G.section('JE GEGEVENS BEWAREN')}<p>Exporteer je planning, trainingen, voorraad, metingen en lokale groepen als bestand. Foto’s blijven op dit toestel en zitten niet in deze back-up.</p>${action(icon('download')+' Gegevens exporteren','export')}<label class="file-button secondary">${icon('upload')} Gegevens importeren<input type="file" id="backup-import" accept="application/json,.json"></label><p class="notice">Verwijder je de app, dan verdwijnen ook je lokale gegevens en foto’s. Er is geen serverkopie om ze terug te halen.</p>${G.data.legacy?'<p class="notice">Je oorspronkelijke plannerarchief blijft in je gegevensback-up bewaard.</p>':''}<p class="version-note">Gym Planner 2.1.0 · op jouw toestel</p>`;
 G.pages.privacy=()=>G.header('ALLEEN OP JOUW TOESTEL','Je gegevens zijn van jou','settings')+`
  <section class="privacy-callout"><span class="mini-icon">${icon('lock')}</span><div><h2>Foto’s verlaten deze app niet.</h2><p>De app bewaart een lokale kopie zodat je je voortgang later kunt bekijken en vergelijken. Er wordt geen foto naar een server, AI-dienst of andere gebruiker verstuurd.</p></div></section>
  <div class="list"><div class="row"><div><h3>Geen cloudopslag vanuit de app</h3><p>${GymNative.available?'De eigen foto- en gegevensbestanden van deze app zijn uitgesloten van iCloud- en computerback-ups.':'In deze browser gebruiken we lokale browseropslag.'} Als je een bestaande foto uit je fotobibliotheek kiest, blijft de oorspronkelijke foto onder de instellingen van die bibliotheek vallen.</p></div></div><div class="row"><div><h3>Jij kiest wat je kopieert</h3><p>Voor AI kopieer je alleen je ingevulde trainingsvoorkeuren. De AI-app waarin je ze plakt, bepaalt zelf hoe die tekst wordt verwerkt. Foto’s worden nooit meegenomen.</p></div></div><div class="row"><div><h3>Groepen blijven lokaal</h3><p>Er is geen online synchronisatie. Een gedeelde challenge-code bevat alleen de challenge, geen foto’s of privéranglijst.</p></div></div><div class="row"><div><h3>Verwijderen is lokaal verwijderen</h3><p>Een foto verwijderen wist de kopie in deze app. Verwijderen van de app wist de lokale opslag; we hebben geen serverkopie om die te herstellen.</p></div></div></div>${button('Terug naar instellingen','settings')}`;
 G.pages.premium=()=>G.header('MEER SAMEN DOEN','Premium','settings')+`
  <section class="premium-hero"><span class="premium-badge">${icon('crown')} PREMIUM</span><h2>Daag elkaar uit.</h2><p>Maak je eigen gymgroepen en start challenges. Je eigen trainingen, voorraad, gewicht, foto’s en AI-prompts blijven gratis.</p></section>
  <div class="feature-comparison"><div><span class="eyebrow">ALTIJD GRATIS</span><ul><li>Trainingen, planning en PR’s</li><li>Producten, gebruik en voorraad</li><li>Gewicht en lokale voortgangsfoto’s</li><li>Prompt voor je eigen AI + plan importeren</li><li>Meedoen aan een gedeelde challenge</li></ul></div><div><span class="eyebrow">PREMIUM</span><ul><li>Eigen groepen aanmaken</li><li>Zelf challenges starten</li><li>Groepen en deelnemers samenstellen</li></ul></div></div>
  <section class="premium-test"><div class="split"><div class="grow"><h3>Premium-teststand</h3><p>${G.isPremium()?'Aan · Premiumfuncties zijn ontgrendeld.':'Uit · je gebruikt nu de gratis versie.'}</p></div>${action(`<span class="switch-track"><span></span></span><span class="sr-only">Premium-teststand</span>`,'premium-toggle',`role="switch" aria-checked="${G.isPremium()}" aria-label="Premium-teststand"`,'setting-switch')}</div><p>Dit is alleen een testschakelaar. Er wordt niets gekocht, afgeschreven of automatisch verlengd.</p>${action(G.isPremium()?'Terug naar gratis':'Premium gratis testen','premium-toggle','',G.isPremium()?'secondary':'primary')}</section>
  <p class="notice">Groepen en resultaten staan op dit toestel. Online vrienden, synchronisatie en echte betalingen zijn nog niet aangesloten.</p>${button('Bekijk je groepen','social',{},'secondary')}`;
 let toggling=false;
 G.actions['premium-toggle']=async()=>{if(toggling)return;toggling=true;try{const enabled=!G.isPremium();if(await G.commit(d=>{d.settings.premiumPreview=enabled;}))G.toast(enabled?'Premium-teststand aan. Er is niets gekocht.':'Je gebruikt weer gratis. Je gegevens blijven bewaard.');}finally{toggling=false;}};
})();
