(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GymSocialModel=api;})(globalThis,function(){
 'use strict';
 const fail=m=>{throw Error(m);};
 const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
 const id=v=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,99}$/.test(v);
 const text=(v,max)=>typeof v==='string'&&!!v.trim()&&v.length<=max;
 const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(new Date(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
 const positive=v=>typeof v==='number'&&Number.isFinite(v)&&v>0&&v<=1000000;
 const canCreate=premium=>premium===true;
 const requirePremium=premium=>{if(!canCreate(premium))fail('Groepen en challenges maken hoort bij Premium. Zet de testversie aan in Instellingen.');};
 function unique(list,label,max){if(!Array.isArray(list)||list.length>max)fail('Ongeldige lijst: '+label+'.');const seen=new Set();for(const item of list){if(!object(item)||!id(item.id)||seen.has(item.id))fail('Ongeldige of dubbele identificatie bij '+label+'.');seen.add(item.id);}return seen;}
 function members(list){const ids=unique(list,'deelnemers',50);if(!ids.has('self'))fail('Je eigen deelname ontbreekt.');for(const m of list)if(!text(m.name,60))fail('Ongeldige naam van een deelnemer.');return ids;}
 function challengeFields(c){if(!object(c)||!id(c.id)||!text(c.title,80)||!['reps','kg'].includes(c.metric)||!positive(c.target)||(c.metric==='reps'&&!Number.isInteger(c.target))||!date(c.start)||!date(c.end)||c.end<c.start)fail('Vul een challenge, een positief doel en geldige begin- en einddatum in.');}
 const initial=()=>({groups:[],challenges:[]});
 function validate(s){if(!object(s))fail('Ongeldige groepsgegevens.');const groups=unique(s.groups,'groepen',100);unique(s.challenges,'challenges',500);for(const g of s.groups){if(!text(g.name,60))fail('Ongeldige groepsnaam.');members(g.members);}for(const c of s.challenges){challengeFields(c);if(!['created','joined'].includes(c.origin)||(c.groupId!==null&&!groups.has(c.groupId))||(c.origin==='joined'&&c.groupId!==null))fail('Ongeldige groep bij de challenge.');const ids=members(c.members);if(c.origin==='joined'&&(c.members.length!==1||c.members[0].id!=='self'))fail('Een gedeelde challenge bewaart alleen je eigen resultaten.');unique(c.entries,'resultaten',10000);for(const r of c.entries)if(!ids.has(r.memberId)||!date(r.date)||r.date<c.start||r.date>c.end||!positive(r.value)||(c.metric==='reps'&&!Number.isInteger(r.value))||typeof r.note!=='string'||r.note.length>200)fail('Ongeldig challengeresultaat.');}return s;}
 function group(s,groupId){const g=s.groups.find(x=>x.id===groupId);if(!g)fail('Deze groep bestaat niet meer.');return g;}
 function challenge(s,challengeId){const c=s.challenges.find(x=>x.id===challengeId);if(!c)fail('Deze challenge bestaat niet meer.');return c;}
 function createGroup(s,values,premium){requirePremium(premium);if(!id(values.id)||s.groups.some(g=>g.id===values.id)||!text(values.name,60)||s.groups.length>=100)fail('Geef de groep een geldige, unieke naam en identificatie.');const g={id:values.id,name:values.name.trim(),members:[{id:'self',name:'Ik'}]};s.groups.push(g);return g;}
 function renameGroup(s,groupId,name,premium){requirePremium(premium);if(!text(name,60))fail('Vul een groepsnaam in.');group(s,groupId).name=name.trim();}
 function addMember(s,groupId,member,premium){requirePremium(premium);const g=group(s,groupId);if(!id(member.id)||g.members.some(m=>m.id===member.id)||!text(member.name,60)||g.members.length>=50)fail('Vul een geldige naam voor een nieuwe deelnemer in.');g.members.push({id:member.id,name:member.name.trim()});}
 function removeMember(s,groupId,memberId){const g=group(s,groupId);if(memberId==='self')fail('Je eigen deelname blijft in de groep.');g.members=g.members.filter(m=>m.id!==memberId);}
 function deleteGroup(s,groupId){group(s,groupId);s.groups=s.groups.filter(g=>g.id!==groupId);s.challenges=s.challenges.filter(c=>c.groupId!==groupId);}
 function createChallenge(s,values,premium){requirePremium(premium);challengeFields(values);const g=group(s,values.groupId);if(s.challenges.some(c=>c.id===values.id)||s.challenges.length>=500)fail('Deze challenge bestaat al, of de lijst is vol.');const c={id:values.id,title:values.title.trim(),metric:values.metric,target:values.target,start:values.start,end:values.end,groupId:g.id,origin:'created',members:g.members.map(m=>({...m})),entries:[]};s.challenges.push(c);return c;}
 function addEntry(s,challengeId,entry,today){const c=challenge(s,challengeId);if(!id(entry.id)||c.entries.some(r=>r.id===entry.id)||c.entries.length>=10000||!c.members.some(m=>m.id===entry.memberId)||!date(entry.date)||entry.date<c.start||entry.date>c.end||(today&&entry.date>today)||!positive(entry.value)||(c.metric==='reps'&&!Number.isInteger(entry.value))||typeof entry.note!=='string'||entry.note.length>200)fail('Kies een deelnemer, een datum binnen de challenge en een geldige score. Een toekomstige score kun je nog niet loggen.');c.entries.push({...entry});}
 function removeEntry(s,challengeId,entryId){const c=challenge(s,challengeId);c.entries=c.entries.filter(r=>r.id!==entryId);}
 function leaderboard(c){return c.members.map(m=>{const rows=c.entries.filter(r=>r.memberId===m.id);return {...m,count:rows.length,value:rows.length?(c.metric==='reps'?rows.reduce((n,r)=>n+r.value,0):Math.max(...rows.map(r=>r.value))):null};}).sort((a,b)=>(b.value??-1)-(a.value??-1)||a.name.localeCompare(b.name));}
 function shareCode(c){challengeFields(c);return JSON.stringify({type:'gym-challenge',version:1,id:c.id,title:c.title,metric:c.metric,target:c.target,start:c.start,end:c.end});}
 function parseShare(raw){if(typeof raw!=='string'||raw.length>2000)fail('De challengecode is leeg of te lang.');let c;try{c=JSON.parse(raw);}catch{fail('Plak een volledige challengecode uit de app.');}if(!object(c)||c.type!=='gym-challenge'||c.version!==1||Object.keys(c).sort().join(',')!=='end,id,metric,start,target,title,type,version')fail('Deze challengecode heeft een ongeldig formaat.');challengeFields(c);return {id:c.id,title:c.title,metric:c.metric,target:c.target,start:c.start,end:c.end};}
 function joinChallenge(s,raw){const c=parseShare(raw);if(s.challenges.some(x=>x.id===c.id))fail('Deze challenge staat al op dit toestel.');if(s.challenges.length>=500)fail('Je challengeoverzicht is vol.');const joined={...c,groupId:null,origin:'joined',members:[{id:'self',name:'Ik'}],entries:[]};s.challenges.push(joined);return joined;}
 return {initial,validate,canCreate,group,challenge,createGroup,renameGroup,addMember,removeMember,deleteGroup,createChallenge,addEntry,removeEntry,leaderboard,shareCode,parseShare,joinChallenge};
});
