(function(){
 'use strict';
 const G=Gym,M=GymSocialModel,C=GymCore,{e,icon,button,header,section,fmt,dateLabel}=G;
 const state=()=>G.data.social;
 const premium=()=>G.isPremium();
 const gate=()=>{if(premium())return true;G.navigate('premium');G.toast('Maken hoort bij Premium. Meedoen is gratis.');return false;};
 const action=(label,name,attrs='',cls='secondary')=>`<button type="button" class="${cls}" data-action="${name}" ${attrs}>${label}</button>`;
 const groupCount=groupId=>{const n=state().challenges.filter(c=>c.groupId===groupId).length;return n+' '+(n===1?'challenge':'challenges');};
 const premiumLabel=()=>premium()?'':'<span class="social-plan-label">Premium</span>';
 const local=()=>`<div class="social-status"><span>${icon('smartphone')} Alleen op dit toestel</span><details class="social-info"><summary>Hoe werkt dit?</summary><p>Je bewaart groepen en scores lokaal. Er zijn nog geen online accounts, uitnodigingen of gedeelde ranglijsten. Een groepscode kopieert alleen de groepsnaam en challengedoelen. Namen, scores en foto's worden niet meegestuurd.</p><p>Een groep of challenge maken is Premium. Meedoen is gratis. Premium kun je nu gratis aanzetten in Instellingen op Vandaag.</p></details></div>`;
 const score=(c,n)=>n===null?'Nog geen score':`${fmt(n)} ${c.metric==='reps'?'reps':'kg'}`;
 const dates=c=>`${dateLabel(c.start)} – ${dateLabel(c.end)}`;
 const status=c=>G.today()<c.start?'Binnenkort':G.today()>c.end?'Afgelopen':'Actief';
 const progress=c=>{const own=M.leaderboard(c).find(x=>x.id==='self');return {value:own.value,pct:Math.min(100,(own.value||0)/c.target*100)};};
 const challengeRow=c=>{const p=progress(c);return button(`<span class="grow"><strong>${e(c.title)}</strong><small>${e(dates(c))} · ${status(c)}</small><span class="social-challenge-progress"><span style="width:${p.pct}%"></span></span></span><span class="social-row-score">${p.value===null?'—':fmt(p.value)} / ${fmt(c.target)}<small>${c.metric==='reps'?'reps':'kg'}</small></span>${icon('chevron-right')}`,'socialChallenge',{challengeId:c.id,groupId:c.groupId},'row row-link social-open');};
 G.pages.social=()=>{
  const s=state();
  return header('','Vriendengroepen')+local()+
   (s.groups.length?`<div class="list social-group-list">${s.groups.map(g=>button(`<span class="mini-icon">${icon('users')}</span><span class="grow"><strong>${e(g.name)}</strong><small>${groupCount(g.id)}</small></span>${icon('chevron-right')}`,'socialGroup',{groupId:g.id},'row row-link social-open')).join('')}</div>`:`<p class="social-empty">Train samen met je vrienden. Maak een groep of voeg er een toe met een groepscode.</p>`)+
   `<div class="social-entry-actions">${action(icon('plus')+' Groep maken '+premiumLabel(),'social-new-group','','primary')}${button(icon('clipboard-paste')+' Groepscode invoeren','socialJoin',{groupId:null},'secondary')}</div>`+
   (s.legacyChallenges.length?`<details class="social-legacy-import"><summary>Eerdere challenges (${s.legacyChallenges.length})</summary><p>Je eerdere scores blijven hier leesbaar. Open een vriendengroep om een challenge daar verder bij te houden.</p>${s.legacyChallenges.map(c=>`<details class="social-group-tools"><summary>${e(c.title)}</summary><p>${e(dates(c))} · Doel ${e(score(c,c.target))}</p><div class="list">${M.leaderboard(c).map(m=>`<div class="row"><span class="grow">${e(m.name)}</span><span>${e(score(c,m.value))}</span></div>`).join('')}</div>${c.entries.length?`<div class="list">${[...c.entries].reverse().slice(0,50).map(r=>`<div class="row"><div class="grow"><strong>${e(c.members.find(m=>m.id===r.memberId).name)} · ${e(score(c,r.value))}</strong><small>${dateLabel(r.date)}${r.note?' · '+e(r.note):''}</small></div></div>`).join('')}</div>`:''}</details>`).join('')}</details>`:'');
 };
 G.actions['social-new-group']=()=>{if(gate())G.navigate('socialGroupEdit',{groupId:null});};
 G.pages.socialGroupEdit=()=>{const g=state().groups.find(x=>x.id===G.ui.groupId);return header('',g?'Groepsnaam':'Vriendengroep maken',g?'socialGroup':'social')+(premium()?`<form class="fields" data-form="social-group"><label>Groepsnaam<input name="name" required maxlength="60" data-autofocus value="${e(g?.name||'')}" placeholder="Bijvoorbeeld: Gym crew"></label><button class="primary" type="submit">${g?'Opslaan':'Groep maken'}</button></form>`:button('Premium bekijken','premium'));};
 G.forms['social-group']=async f=>{if(!gate())return;const existing=G.ui.groupId,id=existing||G.uid(),name=f.elements.name.value.trim();if(await G.commit(d=>{if(existing)M.renameGroup(d.social,id,name,premium());else M.createGroup(d.social,{id,name},premium());}))G.navigate('socialGroup',{groupId:id});};
 G.pages.socialGroup=()=>{
  const g=state().groups.find(x=>x.id===G.ui.groupId);if(!g)return header('Vriendengroepen','Groep niet gevonden','social');
  const challenges=state().challenges.filter(c=>c.groupId===g.id);
  return header('VRIENDENGROEP',g.name,'social')+local()+
   `<div class="social-group-summary">${section('Challenges',action(icon('plus')+' Challenge maken '+premiumLabel(),'social-new-challenge','','text-button'))}</div>`+
   (challenges.length?`<div class="list social-challenge-list">${challenges.map(challengeRow).join('')}</div>`:'<p class="social-empty">Nog geen challenges in deze groep.</p>')+
   `<details class="social-group-share"><summary>${icon('copy')} Groepscode delen</summary><p>Deel deze code zelf met vrienden. Ze krijgen de groepsnaam en ${challenges.length} ${challenges.length===1?'challengedoel':'challengedoelen'}, zonder namen of scores.</p><label class="social-code-label">Groepscode<textarea class="code-input" readonly aria-label="Groepscode">${e(M.groupCode(state(),g.id))}</textarea></label>${action(icon('copy')+' Code kopiëren','social-copy-group','','secondary')}</details>`+
   `<details class="social-group-tools"><summary>${icon('users')} Namen op dit toestel (${g.members.length})</summary><p>Voeg namen toe om scores handmatig bij te houden. Nieuwe namen doen mee aan challenges die je daarna maakt.</p><div class="list">${g.members.map(m=>`<div class="row"><span class="grow">${e(m.name)}</span>${m.id!=='self'?action(icon('x'),'social-remove-member',`data-id="${e(m.id)}" aria-label="${e(m.name)} uit groep verwijderen"`,'icon-button'):''}</div>`).join('')}</div>`+(premium()?`<form class="fields" data-form="social-member"><label>Naam<input name="name" maxlength="60" required placeholder="Naam van je trainingsmaatje"></label><button type="submit" class="secondary">Naam toevoegen</button></form>`:button('Namen toevoegen · Premium','premium',{},'secondary'))+'</details>'+
   `<details class="social-group-tools"><summary>${icon('settings-2')} Groep beheren</summary><div class="social-action-line">${button('Naam wijzigen','socialGroupEdit',{groupId:g.id},'text-button')}${action('Groep verwijderen','social-delete-group','','text-button danger')}</div><details class="social-legacy-import"><summary>Eerdere challenges</summary>`+
   (state().legacyChallenges.length?`<p>Zet een eerder bewaarde challenge in deze groep. Alle bestaande scores blijven behouden.</p><div class="list">${state().legacyChallenges.map(c=>`<div class="row"><div class="grow"><strong>${e(c.title)}</strong><small>${e(dates(c))} · ${c.entries.length} scores</small></div>${action('Overzetten','social-attach-legacy',`data-id="${e(c.id)}"`,'text-button')}</div>`).join('')}</div>`:'')+
   `<form class="fields" data-form="social-legacy-join"><label>Oude challengecode<textarea name="code" class="code-input" required maxlength="2000" spellcheck="false" placeholder="Plak een code uit een eerdere appversie"></textarea></label><button class="secondary" type="submit">Aan deze groep toevoegen</button></form></details></details>`;
 };
 G.actions['social-delete-group']=()=>{const groupId=G.ui.groupId;G.confirm('Groep verwijderen?','De groep, bijbehorende challenges en scores worden van dit toestel verwijderd.',async()=>{if(await G.commit(d=>M.deleteGroup(d.social,groupId)))G.navigate('social');});};
 G.forms['social-member']=async f=>{if(!gate())return;const member={id:G.uid(),name:f.elements.name.value.trim()},groupId=G.ui.groupId;if(await G.commit(d=>M.addMember(d.social,groupId,member,premium())))G.toast('Naam toegevoegd.');};
 G.actions['social-remove-member']=el=>{const groupId=G.ui.groupId,id=el.dataset.id;G.confirm('Naam verwijderen?','Bestaande challenges en scores blijven behouden.',()=>G.commit(d=>M.removeMember(d.social,groupId,id)));};
 G.actions['social-new-challenge']=()=>{M.group(state(),G.ui.groupId);if(gate())G.navigate('socialChallengeNew',{groupId:G.ui.groupId});};
 G.pages.socialChallengeNew=()=>{const g=state().groups.find(x=>x.id===G.ui.groupId);if(!g)return header('Vriendengroepen','Kies eerst een groep','social');return header(g.name,'Challenge maken','socialGroup')+(premium()?`<form class="fields" data-form="social-challenge"><label>Naam<input name="title" maxlength="80" required data-autofocus placeholder="Bijvoorbeeld: Bench weekrecord"></label><label>Doel meten<select name="metric"><option value="kg">Zwaarste lift (kg)</option><option value="reps">Totaal herhalingen</option></select></label><label>Doel<input name="target" inputmode="decimal" required placeholder="Bijvoorbeeld 80"></label><div class="pair"><label>Van<input name="start" type="date" required value="${G.today()}"></label><label>Tot en met<input name="end" type="date" required value="${C.addDays(G.today(),6)}"></label></div><button class="primary" type="submit">Challenge maken</button></form>`:button('Premium bekijken','premium'));};
 G.forms['social-challenge']=async f=>{if(!gate())return;const values={id:G.uid(),groupId:G.ui.groupId,title:f.elements.title.value.trim(),metric:f.elements.metric.value,target:C.parse(f.elements.target.value),start:f.elements.start.value,end:f.elements.end.value};if(await G.commit(d=>M.createChallenge(d.social,values,premium())))G.navigate('socialChallenge',{challengeId:values.id,groupId:values.groupId});};
 G.pages.socialChallenge=()=>{
  const c=state().challenges.find(x=>x.id===G.ui.challengeId);if(!c)return header('Vriendengroepen','Challenge niet gevonden','social');
  const g=M.group(state(),c.groupId),rows=M.leaderboard(c),p=progress(c),canLog=G.today()>=c.start,latest=G.today()<c.end?G.today():c.end;
  return header(g.name,c.title,'socialGroup')+`<p class="social-challenge-date">${e(dates(c))} · ${status(c)}</p>`+
   `<section class="social-goal"><div class="social-score-heading"><span>Jouw voortgang</span><strong>${p.value===null?'—':fmt(p.value)} <small>/ ${fmt(c.target)} ${c.metric==='reps'?'reps':'kg'}</small></strong></div><div class="track" role="progressbar" aria-label="Jouw challengedoel" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(p.pct)}"><span style="width:${p.pct}%"></span></div></section>`+
   (canLog?`<form class="fields social-score-form" data-form="social-score">${c.members.length>1?`<label>Voor wie?<select name="memberId">${c.members.map(m=>`<option value="${e(m.id)}">${e(m.name)}</option>`).join('')}</select></label>`:'<input type="hidden" name="memberId" value="self">'}<div class="social-score-entry"><label>${c.metric==='reps'?'Herhalingen':'Gewicht (kg)'}<input name="value" inputmode="${c.metric==='reps'?'numeric':'decimal'}" required placeholder="0"></label><button class="primary" type="submit">Opslaan</button></div><details class="form-optional"><summary>Datum of notitie</summary><label>Datum<input name="date" type="date" required min="${c.start}" max="${latest}" value="${latest}"></label><label>Notitie<input name="note" maxlength="200"></label></details></form>`:`<p>Scores invoeren kan vanaf ${dateLabel(c.start)}.</p>`)+
   section(c.origin==='joined'?'Jouw scores':'Scores op dit toestel')+`<div class="list">${rows.map((m,i)=>`<div class="row"><span class="social-rank">${m.count?i+1:'—'}</span><span class="grow">${e(m.name)}</span><span class="social-row-score">${e(score(c,m.value))}</span></div>`).join('')}</div>`+
   (c.entries.length?`<details class="social-group-tools"><summary>Registraties (${c.entries.length})</summary><div class="list">${[...c.entries].reverse().slice(0,50).map(r=>`<div class="row"><div class="grow"><strong>${e(c.members.find(m=>m.id===r.memberId).name)} · ${e(score(c,r.value))}</strong><small>${dateLabel(r.date)}${r.note?' · '+e(r.note):''}</small></div>${action(icon('trash-2'),'social-delete-score',`data-id="${e(r.id)}" aria-label="Score van ${e(dateLabel(r.date))} verwijderen"`,'icon-button')}</div>`).join('')}</div></details>`:'')+
   `<div class="social-status"><span>${icon('smartphone')} Alleen op dit toestel</span></div>`+action(c.origin==='joined'?'Challenge verlaten':'Challenge verwijderen','social-delete-challenge','','text-button danger');
 };
 G.forms['social-score']=async f=>{const challengeId=G.ui.challengeId,entry={id:G.uid(),memberId:f.elements.memberId.value,value:C.parse(f.elements.value.value),date:f.elements.date.value,note:f.elements.note.value.trim()};if(await G.commit(d=>M.addEntry(d.social,challengeId,entry,G.today())))G.toast('Score bewaard.');};
 G.actions['social-delete-score']=el=>{const challengeId=G.ui.challengeId,id=el.dataset.id;G.confirm('Score verwijderen?','Deze registratie wordt van dit toestel verwijderd.',()=>G.commit(d=>M.removeEntry(d.social,challengeId,id)));};
 G.actions['social-delete-challenge']=()=>{const c=M.challenge(state(),G.ui.challengeId),id=c.id,groupId=c.groupId;G.confirm('Challenge verwijderen?','De challenge en de bijbehorende scores worden van dit toestel verwijderd.',async()=>{if(await G.commit(d=>{d.social.challenges=d.social.challenges.filter(x=>x.id!==id);}))G.navigate('socialGroup',{groupId});});};
 G.actions['social-copy-group']=async()=>{await G.copyText(M.groupCode(state(),G.ui.groupId));G.toast('Groepscode gekopieerd.');};
 G.pages.socialJoin=()=>header('MEEDOEN IS GRATIS','Groepscode invoeren','social')+`<form class="fields" data-form="social-join-preview"><label>Code van je vriendengroep<textarea name="code" class="code-input" required maxlength="200000" spellcheck="false" data-autofocus placeholder="Plak de groepscode"></textarea></label><button class="primary" type="submit">Groep bekijken</button></form><p class="notice">De groep en challengedoelen komen op jouw toestel. Scores worden niet gesynchroniseerd.</p>`;
 G.forms['social-join-preview']=f=>{const raw=f.elements.code.value,g=M.parseGroupShare(raw),existing=state().groups.some(x=>x.id===g.id),count=g.challenges.filter(c=>!state().challenges.some(x=>x.id===c.id)).length;G.confirm(existing?'Nieuwe challenges toevoegen?':g.name+' toevoegen?',`${count} ${count===1?'challengedoel':'challengedoelen'} op dit toestel. Bestaande scores blijven behouden. Er wordt niets online gedeeld.`,async()=>{if(await G.commit(d=>M.joinGroup(d.social,raw)))G.navigate('socialGroup',{groupId:g.id});});};
 G.actions['social-attach-legacy']=el=>{const groupId=G.ui.groupId,id=el.dataset.id,g=M.group(state(),groupId);G.confirm('Naar '+g.name+' verplaatsen?','De challenge en alle bestaande scores blijven behouden.',async()=>{if(await G.commit(d=>M.attachLegacy(d.social,id,groupId)))G.navigate('socialChallenge',{groupId,challengeId:id});});};
 G.forms['social-legacy-join']=f=>{const raw=f.elements.code.value,c=M.parseShare(raw),groupId=G.ui.groupId,g=M.group(state(),groupId);G.confirm(c.title+' toevoegen?',`Deze challenge komt in ${g.name}. Alleen je eigen nieuwe scores worden bijgehouden.`,async()=>{if(await G.commit(d=>M.joinChallenge(d.social,raw,groupId)))G.navigate('socialChallenge',{groupId,challengeId:c.id});});};
 // Old navigation history remains safe; new sharing always includes the friend group.
 G.pages.socialShare=()=>{const c=state().challenges.find(x=>x.id===G.ui.challengeId),g=c&&state().groups.find(x=>x.id===c.groupId);return header('Vriendengroepen','Groepscode','social')+(g?button('Open '+e(g.name),'socialGroup',{groupId:g.id},'primary'):'<p>Open eerst een vriendengroep.</p>');};
})();
