(function(){
 'use strict';
 const pending=new Map();let seq=0;
 window.GymNative={available:!!window.webkit?.messageHandlers?.gym,request(action,payload={}){return new Promise((resolve,reject)=>{if(!this.available)return reject(Error('Alleen beschikbaar in de iPhone-app.'));const id='r'+(++seq);const timer=['exportBackup','notifications'].includes(action)?null:setTimeout(()=>{pending.delete(id);reject(Error('Opslaan duurt te lang. Probeer opnieuw.'));},45000);pending.set(id,{resolve,reject,timer});try{window.webkit.messageHandlers.gym.postMessage({id,action,payload});}catch(e){clearTimeout(timer);pending.delete(id);reject(e);}});},receive(msg){const p=pending.get(msg.id);if(!p)return;clearTimeout(p.timer);pending.delete(msg.id);msg.ok?p.resolve(msg.result):p.reject(Error(msg.error||'De lokale opslag is niet beschikbaar.'));}};
 let dbPromise;
 function db(){return dbPromise??=(new Promise((resolve,reject)=>{const req=indexedDB.open('gym-local',1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Sluit andere tabbladen van de app en probeer opnieuw.'));}));}
 async function local(mode,value){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('state',mode),store=tx.objectStore('state');const req=mode==='readonly'?store.get('current'):store.put(value,'current');let result;req.onsuccess=()=>{result=req.result;};tx.oncomplete=()=>resolve(result??null);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Lokale opslag is afgebroken.'));});}
 window.GymStorage={async load(){return GymNative.available?GymNative.request('loadState'):local('readonly');},async save(state){return GymNative.available?GymNative.request('saveState',{state}):local('readwrite',state);},async export(data){const json=JSON.stringify(data,null,2);if(GymNative.available)return GymNative.request('exportBackup',{json});const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gym-planner-'+GymCore.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}};
})();

